'use client';

import { useCallback, useEffect, useState } from 'react';

// Guest-portal-only design system. Semantic variables keep dark and light modes
// readable; no workflow may rely on translucent white body copy for contrast.
export const PORTAL_CSS = `
.gp-v2{--gp-bg:#0b0f0e;--gp-surface:#131a18;--gp-surface-2:#0f1514;--gp-surface-3:#1a2320;--gp-text:#f2f5f4;--gp-muted:#a7b4b0;--gp-faint:#7d8a86;--gp-border:rgba(255,255,255,.1);--gp-border-strong:rgba(255,255,255,.17);--gp-ghost-bg:rgba(255,255,255,.07);--gp-on-primary:#06201c;--gp-on-accent:#2a1408;--gp-icon:var(--gp-primary);--gp-primary-soft:rgba(51,230,212,.12);--gp-accent-text:#ffb08f;--gp-accent-soft-bg:rgba(255,138,92,.14);--gp-accent-soft-border:rgba(255,138,92,.4);--gp-danger-text:#ff9d8a;--gp-danger-bg:rgba(255,107,84,.12);--gp-danger-border:rgba(255,107,84,.4);--gp-backdrop:rgba(3,7,6,.65);--gp-art-bg:linear-gradient(135deg,rgba(82,203,222,.16),rgba(118,152,249,.12));min-height:100dvh;background:var(--gp-bg);color:var(--gp-text);color-scheme:dark;font-family:var(--font-portal-sans),system-ui,sans-serif;-webkit-font-smoothing:antialiased}
.gp-v2.gp-light{--gp-bg:#f4f6f5;--gp-surface:#fff;--gp-surface-2:#edf1ef;--gp-surface-3:#e8eeeb;--gp-text:#152019;--gp-muted:#4f5f58;--gp-faint:#68786f;--gp-border:rgba(21,32,25,.12);--gp-border-strong:rgba(21,32,25,.22);--gp-ghost-bg:rgba(21,32,25,.06);--gp-icon:#0a7c6e;--gp-primary-soft:rgba(13,124,110,.1);--gp-accent-text:#a04a24;--gp-accent-soft-bg:rgba(255,138,92,.16);--gp-accent-soft-border:rgba(214,102,58,.45);--gp-danger-text:#b03a22;--gp-danger-bg:rgba(255,107,84,.1);--gp-danger-border:rgba(214,74,44,.4);--gp-backdrop:rgba(21,32,25,.35);--gp-art-bg:linear-gradient(135deg,rgba(82,203,222,.2),rgba(118,152,249,.14));color-scheme:light}
.gp-v2 button{font-family:inherit}.gp-v2 button:focus-visible,.gp-v2 a:focus-visible,.gp-v2 input:focus-visible,.gp-v2 textarea:focus-visible{outline:2px solid var(--gp-primary);outline-offset:2px}.gp-muted{color:var(--gp-muted)}.gp-alert-text{color:var(--gp-danger-text)}
.gp-wrap{max-width:600px;margin:0 auto;padding:calc(16px + env(safe-area-inset-top)) 16px calc(24px + env(safe-area-inset-bottom));display:flex;flex-direction:column;min-height:100dvh}.gp-header{display:flex;align-items:center;gap:12px;padding:8px 0 16px}.gp-header-text{flex:1;min-width:0}.gp-header-actions{display:flex;gap:8px}.gp-logo{width:40px;height:40px;border-radius:10px;object-fit:cover}.gp-property-name,.gp-step-title,.gp-wf-title{font-family:var(--font-portal-serif),Georgia,serif;font-weight:600}.gp-property-name{font-size:1.35rem}.gp-property-loc,.gp-footer{font-size:.85rem;color:var(--gp-muted)}.gp-footer{text-align:center;font-size:.75rem;color:var(--gp-faint);padding-top:24px}.gp-main{flex:1;display:flex;flex-direction:column}.gp-icon-btn{width:40px;height:40px;border:1px solid var(--gp-border);border-radius:12px;background:var(--gp-surface);color:var(--gp-text);display:flex;align-items:center;justify-content:center;cursor:pointer}.gp-hero{width:100%;height:160px;object-fit:cover;border-radius:16px;border:1px solid var(--gp-border);margin-bottom:16px}.gp-hero-compact{width:100%;height:56px;object-fit:cover;border-radius:12px;border:1px solid var(--gp-border);margin:-6px 0 14px}
.gp-step-title{font-size:1.6rem;margin:8px 0 4px}.gp-step-sub{font-size:.95rem;color:var(--gp-muted);line-height:1.45;margin-bottom:20px}.gp-wf-title{font-size:1.25rem}.gp-wf-header{display:flex;align-items:center;gap:10px;padding:4px 0 14px}.gp-title-row{display:flex;align-items:center;gap:.45rem;margin:0}.gp-card{background:var(--gp-surface);border:1px solid var(--gp-border);border-radius:16px;padding:18px}.gp-btn{width:100%;border:0;border-radius:12px;padding:14px 18px;font-size:1rem;font-weight:600;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:8px}.gp-btn:disabled,.gp-send:disabled{opacity:.5;cursor:not-allowed}.gp-btn-primary,.gp-send{background:var(--gp-primary);color:var(--gp-on-primary)}.gp-btn-accent{background:var(--gp-accent);color:var(--gp-on-accent)}.gp-btn-ghost,.gp-back{background:var(--gp-ghost-bg);color:inherit;border:1px solid var(--gp-border)}.gp-back{display:inline-flex;align-items:center;gap:4px;border-radius:10px;padding:9px 12px;font-size:.88rem;font-weight:600;cursor:pointer;text-decoration:none}
.gp-field{margin-bottom:14px}.gp-label{display:block;font-size:.85rem;font-weight:600;margin-bottom:6px}.gp-input,.gp-textarea{width:100%;box-sizing:border-box;background:var(--gp-surface-2);border:1px solid var(--gp-border-strong);border-radius:12px;color:var(--gp-text);padding:13px 14px;font-size:1rem;font-family:inherit}.gp-input::placeholder,.gp-textarea::placeholder{color:var(--gp-faint)}.gp-input:focus,.gp-textarea:focus{border-color:var(--gp-primary)}.gp-textarea{min-height:90px;resize:vertical}.gp-code-row{display:flex;gap:10px;justify-content:center;margin:18px 0}.gp-code-box{width:58px;height:68px;text-align:center;font-size:1.9rem;font-weight:700;background:var(--gp-surface-2);border:1px solid var(--gp-border-strong);border-radius:14px;color:var(--gp-text)}.gp-error{background:var(--gp-danger-bg);border:1px solid var(--gp-danger-border);color:var(--gp-danger-text);border-radius:12px;padding:11px 14px;margin:12px 0}
.gp-menu-grid,.gp-assist-grid{display:grid;grid-template-columns:1fr;gap:12px;margin-top:18px}@media(min-width:480px){.gp-menu-grid{grid-template-columns:1fr 1fr}.gp-assist-grid{grid-template-columns:repeat(2,1fr)}}.gp-menu-card,.gp-assist-card{display:flex;flex-direction:column;gap:10px;text-align:left;background:var(--gp-surface);border:1px solid var(--gp-border);border-radius:16px;padding:14px;color:inherit;cursor:pointer}.gp-menu-card:hover,.gp-assist-card:hover{border-color:var(--gp-primary)}.gp-menu-title,.gp-assist-title{font-size:1rem;font-weight:700}.gp-menu-blurb,.gp-assist-desc{font-size:.83rem;color:var(--gp-muted);line-height:1.4}.gp-card-art{width:100%;height:88px;border-radius:12px;display:flex;align-items:center;justify-content:center;background:var(--gp-art-bg);border:1px solid var(--gp-border);color:var(--gp-icon)}.gp-assist-card .gp-card-art{height:64px}
.gp-chat-panel{border:1px solid var(--gp-border);border-radius:18px;padding:1rem;min-height:300px;max-height:52vh;overflow-y:auto;background:var(--gp-surface-2)}.gp-msg-row{display:flex;justify-content:flex-start;margin-bottom:.7rem}.gp-msg-row-user{justify-content:flex-end}.gp-msg{max-width:84%;border-radius:18px;padding:.75rem .85rem;background:var(--gp-surface-3);border:1px solid var(--gp-border);color:var(--gp-text);border-bottom-left-radius:4px}.gp-msg-user{background:var(--gp-primary);color:var(--gp-on-primary);border-color:transparent;border-bottom-left-radius:18px;border-bottom-right-radius:4px}.gp-msg-host,.gp-msg-escalation{background:var(--gp-accent-soft-bg);border-color:var(--gp-accent-soft-border)}.gp-msg-tag{font-size:.72rem;font-weight:700;margin-bottom:.3rem;color:var(--gp-accent-text);display:flex;align-items:center;gap:.35rem}.gp-msg-meta{display:flex;gap:.6rem;margin-top:.4rem;font-size:.72rem;color:var(--gp-muted)}.gp-msg-link{border:0;background:none;color:inherit;padding:0;text-decoration:underline;cursor:pointer;font:inherit}.gp-input-row{display:flex;gap:8px;padding-top:4px}.gp-input-row .gp-input{flex:1}.gp-send{width:50px;flex-shrink:0;border:0;border-radius:12px;display:flex;align-items:center;justify-content:center;cursor:pointer}.gp-notice{display:flex;gap:.6rem;border:1px solid var(--gp-accent-soft-border);background:var(--gp-accent-soft-bg);border-radius:14px;padding:.75rem;margin-bottom:.85rem}.gp-empty{padding:40px 20px;text-align:center;color:var(--gp-muted)}
.gp-modal-backdrop{position:fixed;inset:0;z-index:60;padding:12px;background:var(--gp-backdrop);display:flex;align-items:flex-end;justify-content:center}@media(min-width:520px){.gp-modal-backdrop{align-items:center}}.gp-modal{width:100%;max-width:460px;max-height:78vh;background:var(--gp-surface);border:1px solid var(--gp-border-strong);border-radius:18px;display:flex;flex-direction:column}.gp-modal-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid var(--gp-border)}.gp-modal-title{font-size:1rem;font-weight:700;display:flex;align-items:center;gap:.5rem}.gp-modal-body{padding:12px 16px 16px;overflow-y:auto}.gp-modal-sub{font-size:.84rem;color:var(--gp-muted);line-height:1.4}.gp-prompt-list,.gp-picker-list{display:flex;flex-direction:column;gap:8px}.gp-picker-list{max-height:46vh;overflow-y:auto}.gp-prompt-item,.gp-picker-item{width:100%;text-align:left;background:var(--gp-surface-2);border:1px solid var(--gp-border);border-radius:12px;color:var(--gp-text);padding:12px 14px;cursor:pointer}.gp-prompt-item:hover,.gp-picker-item:hover{border-color:var(--gp-primary)}.gp-picker-item-title{font-weight:650}.gp-picker-item-sub{display:block;color:var(--gp-muted);font-size:.78rem;margin-top:2px}.gp-spin{animation:gp-spin 1s linear infinite}@keyframes gp-spin{to{transform:rotate(360deg)}}
`;

export type PortalTheme = 'dark' | 'light';
const THEME_STORAGE_KEY = 'gp-theme';
export function usePortalTheme(){const[theme,setTheme]=useState<PortalTheme>('dark');useEffect(()=>{try{if(localStorage.getItem(THEME_STORAGE_KEY)==='light')setTheme('light')}catch{}},[]);const toggleTheme=useCallback(()=>setTheme(current=>{const next=current==='dark'?'light':'dark';try{localStorage.setItem(THEME_STORAGE_KEY,next)}catch{}return next}),[]);return{theme,toggleTheme}}
