-- GENERATED FILE. Do not edit by hand.
-- Source: field_registry.json (registry_version 1)
-- Regenerate: python3 scripts/registry-sql.py seed
-- CI guard:   python3 scripts/registry-sql.py drift
--
-- Materializes the registry into public.field_registry. Idempotent: re-running
-- reconciles the table to the JSON, including removing fields deleted from the
-- registry. Apply after supabase-migrations-GATE2-REGISTRY.sql.
--
-- registry_checksum: 9344b26b13cf08c70c3e59eaea4b476888b5c12a5d129c188cafb2e3abd24126

BEGIN;

-- Deferred so on_failure_field self-references can be inserted in any order.
SET CONSTRAINTS ALL DEFERRED;

INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'access_backup_method',
    'Backup access method',
    'access_security',
    false,
    'text',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    2.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'If the keypad is dead or the code fails, how else does a guest get in tonight?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'access_code_lifecycle',
    'Access code lifecycle',
    'access_security',
    false,
    'text',
    NULL,
    'host_only'::public.sensitivity_tier,
    'host_private'::public.audience_tier,
    '{"pre-arrival"}'::text[],
    90,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'has_smart_lock',
    false,
    NULL,
    NULL,
    'Does the code change between stays? Who rotates it, and when?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'after_hours_escalation',
    'After-hours escalation',
    'maintenance_escalation',
    false,
    'text',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    1.5,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Who handles a 2am problem if the primary contact does not answer?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'age_child_policy',
    'Age & child policy',
    'policies_money',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'always',
    false,
    NULL,
    'House rules; ''Suitable for children'' / ''infants'' rows.',
    'Any age restrictions? Is the space suitable for infants or children?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'appliance_list',
    'Appliance list',
    'amenities',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    'Amenities section; kitchen and laundry groups.',
    'Which major appliances are available to guests?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'appliance_troubleshooting',
    'Appliance troubleshooting',
    'maintenance_escalation',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    true,
    'maintenance_emergency_contact',
    NULL,
    'Any appliance with a known trick — breaker location, reset button, quirk?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'area_safety_notes',
    'Area safety notes',
    'local_area',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"pre-arrival","mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Anything guests should know about the area after dark?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'audit_verified_at',
    'Verified at',
    'sys_provenance_audit',
    true,
    'date',
    NULL,
    'host_only'::public.sensitivity_tier,
    'system_internal'::public.audience_tier,
    '{"booking"}'::text[],
    NULL,
    'brain_values',
    'verified_at',
    false,
    0.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'System field. Not host-facing.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'automation_gate_decision',
    'Auto-publish gate decision',
    'sys_automations_rules',
    true,
    'enum',
    '["would_have_published", "held_for_host"]'::jsonb,
    'host_only'::public.sensitivity_tier,
    'system_internal'::public.audience_tier,
    '{"booking"}'::text[],
    NULL,
    'brain_values',
    'value',
    false,
    0.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'System field. Not host-facing.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'bed_configuration',
    'Bed count, sizes & configuration',
    'space_details',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","pre-arrival"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.5,
    false,
    'always',
    false,
    NULL,
    '''Where you''ll sleep'' section; per-room bed cards.',
    'How many beds, what sizes, and in which rooms?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'checkin_flexibility',
    'Early check-in policy & fee',
    'access_security',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"booking","pre-arrival"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Can guests check in early, and is there a fee?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'checkin_time',
    'Check-in time',
    'access_security',
    false,
    'time',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","pre-arrival"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    2.0,
    false,
    'always',
    false,
    NULL,
    'House rules / ''Check-in'' row on the listing page.',
    'What time can guests check in?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'checkout_checklist',
    'Checkout checklist',
    'checkout',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"checkout"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.5,
    false,
    'always',
    false,
    NULL,
    NULL,
    'What must a guest do before leaving — dishes, linens, thermostat, lights?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'checkout_time',
    'Checkout time',
    'access_security',
    false,
    'time',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","mid-stay","checkout"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    3.0,
    true,
    'always',
    false,
    NULL,
    'House rules / ''Checkout'' row on the listing page.',
    'What time must guests check out?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'climate_control',
    'Heating & cooling',
    'amenities',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    'Amenities section plus review text mentioning hot/cold rooms.',
    'How do guests control heat and AC, and are there any known weak spots (e.g. ''AC struggles upstairs'')?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'deposit_damage_policy',
    'Deposit & damage policy',
    'policies_money',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"booking","checkout"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'charges_deposit',
    false,
    NULL,
    NULL,
    'Is there a security deposit or damage policy guests should know about?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'door_code_or_entry_method',
    'Door / access code',
    'access_security',
    false,
    'secret',
    NULL,
    'stay_scoped_secret'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay"}'::text[],
    90,
    'brain_values',
    'secret_ref_or_ciphertext',
    true,
    3.0,
    true,
    'always',
    true,
    'access_backup_method',
    NULL,
    'What is the door or building access code? Stored encrypted; never auto-sent.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'elevator_stairs',
    'Elevator or stairs',
    'space_details',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","pre-arrival"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'is_multi_story',
    false,
    NULL,
    'Accessibility features section.',
    'Is there an elevator, or how many flights of stairs?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'entry_method',
    'Entry method / lock type',
    'access_security',
    false,
    'enum',
    '["smart_lock", "keypad", "lockbox", "physical_key", "doorman", "other"]'::jsonb,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"pre-arrival","check-in"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    2.0,
    false,
    'always',
    true,
    'access_backup_method',
    NULL,
    'How do guests get in — smart lock, keypad, lockbox, key handoff, or doorman?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'extra_guest_policy',
    'Extra guest & visitor policy',
    'house_rules',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Are visitors or additional guests allowed, and at what cost?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'floor_number',
    'Floor number',
    'space_details',
    false,
    'string',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"pre-arrival","check-in"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'is_multi_story',
    false,
    NULL,
    NULL,
    'Which floor is the unit on?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'hot_tub_instructions',
    'Hot tub instructions & hours',
    'amenities',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'has_hot_tub',
    true,
    'maintenance_emergency_contact',
    NULL,
    'How is the hot tub operated, what are its hours, and any safety notes?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'key_return_process',
    'Key or code return',
    'checkout',
    false,
    'text',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"checkout"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'How are keys returned, or is the code simply retired?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'late_checkout_policy',
    'Late checkout policy',
    'checkout',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"mid-stay","checkout"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Can a guest check out late, and is there a fee?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'laundry_access',
    'Laundry access & instructions',
    'amenities',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'has_laundry',
    false,
    NULL,
    'Amenities section; ''Washer'' / ''Dryer'' rows.',
    'Is there laundry, where is it, and how is it operated?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'maintenance_emergency_contact',
    'Maintenance / emergency contact',
    'maintenance_escalation',
    false,
    'contact',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay","checkout"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    3.0,
    true,
    'always',
    false,
    NULL,
    NULL,
    'Who does a guest reach for an urgent maintenance problem, and on what number? This anchors every other fallback.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'max_occupancy',
    'Maximum occupancy',
    'space_details',
    false,
    'number',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    'Listing header; ''N guests'' in the summary row.',
    'How many guests can stay?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'minimum_stay',
    'Minimum stay',
    'policies_money',
    false,
    'number',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'always',
    false,
    NULL,
    NULL,
    'What is the minimum number of nights?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'nearest_grocery',
    'Nearest grocery',
    'local_area',
    false,
    'place',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"pre-arrival","mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    3.0,
    true,
    'always',
    false,
    NULL,
    'Neighborhood / ''Where you''ll be'' section.',
    'What is the closest grocery store, and how far is it?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'nearest_pharmacy',
    'Nearest pharmacy',
    'local_area',
    false,
    'place',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'What is the closest pharmacy, and how far is it?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'parking',
    'Parking type & location',
    'parking',
    false,
    'text',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"booking","pre-arrival","check-in"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    3.0,
    true,
    'always',
    true,
    'parking_overflow_fallback',
    'Amenities section; ''Free parking on premises'' / ''Paid parking'' rows.',
    'Where exactly do guests park — driveway, street, garage, assigned spot? Include the quirks.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'parking_access_instructions',
    'Parking access instructions',
    'parking',
    false,
    'text',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'has_parking',
    false,
    NULL,
    NULL,
    'Any gate code, permit, or garage clearance height guests need?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'parking_cost',
    'Parking cost',
    'parking',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'has_parking',
    false,
    NULL,
    NULL,
    'Is parking free or paid, and how much?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'parking_overflow_fallback',
    'Parking fallback',
    'parking',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'has_parking',
    false,
    NULL,
    NULL,
    'If the spot is taken or the garage is full, where should a guest go instead?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'pet_fee',
    'Pet fee',
    'policies_money',
    false,
    'number',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'allows_pets',
    false,
    NULL,
    NULL,
    'What is the pet fee, and is it per stay or per night?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'pet_policy',
    'Pet policy & fees',
    'policies_money',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    'House rules section; ''Pets allowed'' row.',
    'Are pets allowed? Any fee, size, or breed limits?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'plumbing_troubleshooting',
    'Plumbing troubleshooting',
    'maintenance_escalation',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    true,
    'maintenance_emergency_contact',
    NULL,
    'What should a guest try for a clogged toilet or slow drain before calling you?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'pool_instructions',
    'Pool instructions & hours',
    'amenities',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'has_pool',
    true,
    'maintenance_emergency_contact',
    NULL,
    'What are the pool hours, rules, and any heating or safety notes?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'provenance_source_rank',
    'Provenance source rank',
    'sys_provenance_audit',
    true,
    'enum',
    '["host_verified", "pms_sync", "host_chat", "escalation", "firecrawl", "inferred"]'::jsonb,
    'host_only'::public.sensitivity_tier,
    'system_internal'::public.audience_tier,
    '{"booking"}'::text[],
    NULL,
    'brain_values',
    'source',
    false,
    0.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'System field. Not host-facing.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'quiet_hours',
    'Quiet hours',
    'house_rules',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    'House rules section; ''Quiet hours'' row.',
    'What are the quiet hours, and is there an HOA or city noise rule?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'restaurant_recommendations',
    'Restaurant recommendations',
    'local_area',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"pre-arrival","mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Name two or three nearby places you would actually send a guest to.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'safety_escalation_record',
    'Safety escalation record',
    'sys_safety_escalations',
    true,
    'text',
    NULL,
    'host_only'::public.sensitivity_tier,
    'system_internal'::public.audience_tier,
    '{"mid-stay"}'::text[],
    NULL,
    'brain_values',
    'value',
    false,
    0.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'System field. Not host-facing.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'scrape_log_entry',
    'Scrape log entry',
    'sys_sources_scrape_log',
    true,
    'text',
    NULL,
    'host_only'::public.sensitivity_tier,
    'system_internal'::public.audience_tier,
    '{"booking"}'::text[],
    NULL,
    'brain_values',
    'value',
    false,
    0.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'System field. Not host-facing.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'security_camera_disclosure',
    'Security camera disclosure',
    'access_security',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","pre-arrival"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.5,
    false,
    'has_security_cameras',
    false,
    NULL,
    'Safety & property section; ''Security cameras on property'' row.',
    'Are there any exterior cameras or recording devices? Disclosure is legally required.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'smoking_policy',
    'Smoking policy',
    'house_rules',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'always',
    false,
    NULL,
    'House rules section; ''No smoking'' row.',
    'Is smoking or vaping permitted anywhere on the property?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'transit_options',
    'Transit options',
    'local_area',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","pre-arrival","mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    '''Getting around'' / neighborhood section.',
    'What transit, rideshare, or airport options do guests use?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'trash_schedule',
    'Trash & recycling',
    'house_rules',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay","checkout"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Where does trash go, and is there a collection day guests must handle?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'unexpected_charge_disclosure',
    'Additional charges',
    'policies_money',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.5,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Are there any charges a guest could be surprised by — resort fee, cleaning, utilities, extra guest?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'utility_shutoff_locations',
    'Utility shutoff locations',
    'maintenance_escalation',
    false,
    'text',
    NULL,
    'host_only'::public.sensitivity_tier,
    'staff_ops'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.0,
    false,
    'always',
    false,
    NULL,
    NULL,
    'Where are the water shutoff, breaker panel, and gas valve?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'wifi_network_name',
    'Wi-Fi network name',
    'connectivity',
    false,
    'string',
    NULL,
    'guest_after_verification'::public.sensitivity_tier,
    'guest_prearrival'::public.audience_tier,
    '{"pre-arrival","check-in","mid-stay"}'::text[],
    180,
    'brain_values',
    'value',
    false,
    2.0,
    false,
    'has_wifi',
    true,
    'wifi_troubleshooting',
    'Amenities section; look for ''Wifi'' or ''Internet'' amenity rows.',
    'What is the exact Wi-Fi network name (SSID) guests should join?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'wifi_password',
    'Wi-Fi password',
    'connectivity',
    false,
    'secret',
    NULL,
    'stay_scoped_secret'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"check-in","mid-stay"}'::text[],
    180,
    'brain_values',
    'secret_ref_or_ciphertext',
    true,
    3.0,
    true,
    'has_wifi',
    true,
    'wifi_troubleshooting',
    NULL,
    'What is the Wi-Fi password? It is stored encrypted and never sent to a model.',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'wifi_speed_tier',
    'Internet speed',
    'connectivity',
    false,
    'string',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_public'::public.audience_tier,
    '{"booking","pre-arrival"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    0.5,
    false,
    'always',
    false,
    NULL,
    'Amenities section; ''Fast wifi'' badge often states Mbps.',
    'Roughly what download speed can guests expect?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;
INSERT INTO public.field_registry (
    field_id,
    label,
    domain,
    system_section,
    type,
    enum_values,
    sensitivity_tier,
    default_audience,
    phase,
    ttl_days,
    storage_table,
    storage_column,
    storage_vault,
    gap_weight,
    hard_block,
    applicability,
    requires_on_failure,
    on_failure_field,
    scrape_hint,
    interview_prompt,
    registry_version
) VALUES (
    'wifi_troubleshooting',
    'Wi-Fi troubleshooting / fallback',
    'connectivity',
    false,
    'text',
    NULL,
    'public_guest'::public.sensitivity_tier,
    'guest_instay'::public.audience_tier,
    '{"mid-stay"}'::text[],
    365,
    'brain_values',
    'value',
    false,
    1.5,
    false,
    'always',
    false,
    NULL,
    NULL,
    'If the Wi-Fi is down at 11pm, what should a guest do? Where is the router, and who do they call?',
    1
)
ON CONFLICT (field_id) DO UPDATE SET
  label = EXCLUDED.label,
  domain = EXCLUDED.domain,
  system_section = EXCLUDED.system_section,
  type = EXCLUDED.type,
  enum_values = EXCLUDED.enum_values,
  sensitivity_tier = EXCLUDED.sensitivity_tier,
  default_audience = EXCLUDED.default_audience,
  phase = EXCLUDED.phase,
  ttl_days = EXCLUDED.ttl_days,
  storage_table = EXCLUDED.storage_table,
  storage_column = EXCLUDED.storage_column,
  storage_vault = EXCLUDED.storage_vault,
  gap_weight = EXCLUDED.gap_weight,
  hard_block = EXCLUDED.hard_block,
  applicability = EXCLUDED.applicability,
  requires_on_failure = EXCLUDED.requires_on_failure,
  on_failure_field = EXCLUDED.on_failure_field,
  scrape_hint = EXCLUDED.scrape_hint,
  interview_prompt = EXCLUDED.interview_prompt,
  registry_version = EXCLUDED.registry_version;

-- Reconcile deletions: a field removed from the registry must not linger in the
-- table, or a brain_values row could keep an FK to an undeclared field.
DELETE FROM public.field_registry
WHERE field_id NOT IN (
  'access_backup_method',
  'access_code_lifecycle',
  'after_hours_escalation',
  'age_child_policy',
  'appliance_list',
  'appliance_troubleshooting',
  'area_safety_notes',
  'audit_verified_at',
  'automation_gate_decision',
  'bed_configuration',
  'checkin_flexibility',
  'checkin_time',
  'checkout_checklist',
  'checkout_time',
  'climate_control',
  'deposit_damage_policy',
  'door_code_or_entry_method',
  'elevator_stairs',
  'entry_method',
  'extra_guest_policy',
  'floor_number',
  'hot_tub_instructions',
  'key_return_process',
  'late_checkout_policy',
  'laundry_access',
  'maintenance_emergency_contact',
  'max_occupancy',
  'minimum_stay',
  'nearest_grocery',
  'nearest_pharmacy',
  'parking',
  'parking_access_instructions',
  'parking_cost',
  'parking_overflow_fallback',
  'pet_fee',
  'pet_policy',
  'plumbing_troubleshooting',
  'pool_instructions',
  'provenance_source_rank',
  'quiet_hours',
  'restaurant_recommendations',
  'safety_escalation_record',
  'scrape_log_entry',
  'security_camera_disclosure',
  'smoking_policy',
  'transit_options',
  'trash_schedule',
  'unexpected_charge_disclosure',
  'utility_shutoff_locations',
  'wifi_network_name',
  'wifi_password',
  'wifi_speed_tier',
  'wifi_troubleshooting'
);

COMMIT;
