// Guest-facing strings for party invites and the door-code policy reply
// (2026-10-01). Same locale set, English fallback, and {var} interpolation as
// lib/guest/portal-strings.ts, kept in its own module so the feature ships and
// is reviewed as one unit. Pure data + one pure lookup: safe on client and server.

import { resolveLanguage } from './languages';
import type { PortalT } from './portal-strings';

type Dict = Record<string, string>;

const en: Dict = {
  inviteButton: 'Invite your group',
  inviteTitle: 'Invite your group',
  inviteSub: 'Send this link to the people staying with you. Each person adds their own name, and your host can see who joined.',
  inviteCreating: 'Creating your link…',
  inviteShare: 'Share',
  inviteCopy: 'Copy link',
  inviteCopied: 'Copied',
  inviteText: 'Text',
  inviteSpotsOne: '1 spot left',
  inviteSpotsMany: '{count} spots left',
  inviteExpiry: 'Link stops working after checkout.',
  inviteShareMessage: 'Join our stay at {property}! Check-in info, the house guide, local tips and host chat are all here (works until {date}).',
  inviteErrGeneric: 'Could not create an invite. Please try again.',
  inviteErrNetwork: 'Could not create an invite. Check your connection.',
  inviteErrFull: 'Your group invite is full. Ask your host to add more spots.',
  inviteErrDisabled: 'Your host has turned off group invites.',
  inviteErrEnded: 'This stay has ended, so it can no longer be shared.',
  inviteErrCopy: 'Copy failed. Press and hold the link to copy it.',
  close: 'Close',
  joinTitle: 'You’re invited to join the stay',
  joinSub: 'Get the house guide, check-in details, local tips and a direct line to your host. You’ll add your name next.',
  joinCta: 'Join the stay',
  joining: 'Joining…',
  joinInvalid: 'This invite link is invalid, full, or has expired. Ask the person who sent it for a fresh link, or contact your host.',
  joinError: 'Something went wrong. Please try again.',
  tryAgain: 'Try again',
  loading: 'Loading…',
  doorCodeReply: 'For your security, entry codes aren’t shared in chat. I’ve let your host know, and they’ll reply to you here shortly.',
};

const es: Dict = {
  inviteButton: 'Invita a tu grupo',
  inviteTitle: 'Invita a tu grupo',
  inviteSub: 'Envía este enlace a las personas que se alojan contigo. Cada una añade su nombre y tu anfitrión puede ver quién se ha unido.',
  inviteCreating: 'Creando tu enlace…',
  inviteShare: 'Compartir',
  inviteCopy: 'Copiar enlace',
  inviteCopied: 'Copiado',
  inviteText: 'SMS',
  inviteSpotsOne: 'Queda 1 plaza',
  inviteSpotsMany: 'Quedan {count} plazas',
  inviteExpiry: 'El enlace deja de funcionar después del check-out.',
  inviteShareMessage: '¡Únete a nuestra estancia en {property}! Aquí tienes la información de llegada, la guía de la casa, recomendaciones locales y el chat con el anfitrión (válido hasta el {date}).',
  inviteErrGeneric: 'No se pudo crear la invitación. Inténtalo de nuevo.',
  inviteErrNetwork: 'No se pudo crear la invitación. Revisa tu conexión.',
  inviteErrFull: 'La invitación de tu grupo está completa. Pide a tu anfitrión que añada más plazas.',
  inviteErrDisabled: 'Tu anfitrión ha desactivado las invitaciones de grupo.',
  inviteErrEnded: 'Esta estancia ha terminado y ya no se puede compartir.',
  inviteErrCopy: 'No se pudo copiar. Mantén pulsado el enlace para copiarlo.',
  close: 'Cerrar',
  joinTitle: 'Te han invitado a unirte a la estancia',
  joinSub: 'Accede a la guía de la casa, los detalles de llegada, recomendaciones locales y contacto directo con tu anfitrión. A continuación añadirás tu nombre.',
  joinCta: 'Unirme a la estancia',
  joining: 'Uniéndote…',
  joinInvalid: 'Este enlace de invitación no es válido, está completo o ha caducado. Pide un enlace nuevo a quien te lo envió o contacta con tu anfitrión.',
  joinError: 'Algo salió mal. Inténtalo de nuevo.',
  tryAgain: 'Reintentar',
  loading: 'Cargando…',
  doorCodeReply: 'Por tu seguridad, los códigos de acceso no se comparten en el chat. He avisado a tu anfitrión y te responderá aquí en breve.',
};

const fr: Dict = {
  inviteButton: 'Inviter votre groupe',
  inviteTitle: 'Inviter votre groupe',
  inviteSub: 'Envoyez ce lien aux personnes qui séjournent avec vous. Chacune ajoute son nom, et votre hôte voit qui a rejoint le séjour.',
  inviteCreating: 'Création de votre lien…',
  inviteShare: 'Partager',
  inviteCopy: 'Copier le lien',
  inviteCopied: 'Copié',
  inviteText: 'SMS',
  inviteSpotsOne: '1 place restante',
  inviteSpotsMany: '{count} places restantes',
  inviteExpiry: 'Le lien cesse de fonctionner après le départ.',
  inviteShareMessage: 'Rejoignez notre séjour à {property} ! Infos d’arrivée, guide de la maison, adresses locales et chat avec l’hôte, tout est ici (valable jusqu’au {date}).',
  inviteErrGeneric: 'Impossible de créer l’invitation. Veuillez réessayer.',
  inviteErrNetwork: 'Impossible de créer l’invitation. Vérifiez votre connexion.',
  inviteErrFull: 'L’invitation de votre groupe est complète. Demandez à votre hôte d’ajouter des places.',
  inviteErrDisabled: 'Votre hôte a désactivé les invitations de groupe.',
  inviteErrEnded: 'Ce séjour est terminé, il ne peut plus être partagé.',
  inviteErrCopy: 'La copie a échoué. Appuyez longuement sur le lien pour le copier.',
  close: 'Fermer',
  joinTitle: 'Vous êtes invité à rejoindre le séjour',
  joinSub: 'Accédez au guide de la maison, aux informations d’arrivée, aux adresses locales et à votre hôte directement. Vous ajouterez ensuite votre nom.',
  joinCta: 'Rejoindre le séjour',
  joining: 'Connexion…',
  joinInvalid: 'Ce lien d’invitation n’est pas valide, est complet ou a expiré. Demandez un nouveau lien à la personne qui vous l’a envoyé, ou contactez votre hôte.',
  joinError: 'Une erreur est survenue. Veuillez réessayer.',
  tryAgain: 'Réessayer',
  loading: 'Chargement…',
  doorCodeReply: 'Pour votre sécurité, les codes d’accès ne sont pas partagés dans le chat. J’ai prévenu votre hôte, qui vous répondra ici sous peu.',
};

const de: Dict = {
  inviteButton: 'Deine Gruppe einladen',
  inviteTitle: 'Deine Gruppe einladen',
  inviteSub: 'Schick diesen Link an die Personen, die mit dir übernachten. Jede Person gibt ihren eigenen Namen ein, und dein Gastgeber sieht, wer beigetreten ist.',
  inviteCreating: 'Dein Link wird erstellt…',
  inviteShare: 'Teilen',
  inviteCopy: 'Link kopieren',
  inviteCopied: 'Kopiert',
  inviteText: 'SMS',
  inviteSpotsOne: 'Noch 1 Platz frei',
  inviteSpotsMany: 'Noch {count} Plätze frei',
  inviteExpiry: 'Der Link funktioniert nach dem Check-out nicht mehr.',
  inviteShareMessage: 'Komm mit zu unserem Aufenthalt in {property}! Check-in-Infos, Hausguide, lokale Tipps und der Gastgeber-Chat – alles hier (gültig bis {date}).',
  inviteErrGeneric: 'Die Einladung konnte nicht erstellt werden. Bitte versuche es erneut.',
  inviteErrNetwork: 'Die Einladung konnte nicht erstellt werden. Prüfe deine Verbindung.',
  inviteErrFull: 'Die Einladung deiner Gruppe ist voll. Bitte deinen Gastgeber, weitere Plätze hinzuzufügen.',
  inviteErrDisabled: 'Dein Gastgeber hat Gruppeneinladungen deaktiviert.',
  inviteErrEnded: 'Dieser Aufenthalt ist beendet und kann nicht mehr geteilt werden.',
  inviteErrCopy: 'Kopieren fehlgeschlagen. Halte den Link gedrückt, um ihn zu kopieren.',
  close: 'Schließen',
  joinTitle: 'Du bist eingeladen, dem Aufenthalt beizutreten',
  joinSub: 'Erhalte den Hausguide, Check-in-Details, lokale Tipps und einen direkten Draht zu deinem Gastgeber. Als Nächstes gibst du deinen Namen ein.',
  joinCta: 'Dem Aufenthalt beitreten',
  joining: 'Wird beigetreten…',
  joinInvalid: 'Dieser Einladungslink ist ungültig, voll oder abgelaufen. Bitte die Person, die ihn geschickt hat, um einen neuen Link, oder wende dich an deinen Gastgeber.',
  joinError: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
  tryAgain: 'Erneut versuchen',
  loading: 'Wird geladen…',
  doorCodeReply: 'Zu deiner Sicherheit werden Zugangscodes nicht im Chat geteilt. Ich habe deinen Gastgeber benachrichtigt – er antwortet dir hier in Kürze.',
};

const it: Dict = {
  inviteButton: 'Invita il tuo gruppo',
  inviteTitle: 'Invita il tuo gruppo',
  inviteSub: 'Invia questo link alle persone che soggiornano con te. Ognuno aggiunge il proprio nome e il tuo host può vedere chi si è unito.',
  inviteCreating: 'Creazione del link…',
  inviteShare: 'Condividi',
  inviteCopy: 'Copia link',
  inviteCopied: 'Copiato',
  inviteText: 'SMS',
  inviteSpotsOne: '1 posto rimasto',
  inviteSpotsMany: '{count} posti rimasti',
  inviteExpiry: 'Il link smette di funzionare dopo il check-out.',
  inviteShareMessage: 'Unisciti al nostro soggiorno a {property}! Info di arrivo, guida della casa, consigli locali e chat con l’host, tutto qui (valido fino al {date}).',
  inviteErrGeneric: 'Impossibile creare l’invito. Riprova.',
  inviteErrNetwork: 'Impossibile creare l’invito. Controlla la connessione.',
  inviteErrFull: 'L’invito del tuo gruppo è al completo. Chiedi al tuo host di aggiungere altri posti.',
  inviteErrDisabled: 'Il tuo host ha disattivato gli inviti di gruppo.',
  inviteErrEnded: 'Questo soggiorno è terminato e non può più essere condiviso.',
  inviteErrCopy: 'Copia non riuscita. Tieni premuto il link per copiarlo.',
  close: 'Chiudi',
  joinTitle: 'Sei stato invitato a unirti al soggiorno',
  joinSub: 'Accedi alla guida della casa, ai dettagli del check-in, ai consigli locali e a un contatto diretto con il tuo host. Subito dopo aggiungerai il tuo nome.',
  joinCta: 'Unisciti al soggiorno',
  joining: 'Accesso in corso…',
  joinInvalid: 'Questo link di invito non è valido, è al completo o è scaduto. Chiedi un nuovo link a chi te l’ha inviato oppure contatta il tuo host.',
  joinError: 'Qualcosa è andato storto. Riprova.',
  tryAgain: 'Riprova',
  loading: 'Caricamento…',
  doorCodeReply: 'Per la tua sicurezza, i codici di accesso non vengono condivisi in chat. Ho avvisato il tuo host, che ti risponderà qui a breve.',
};

const pt: Dict = {
  inviteButton: 'Convidar o seu grupo',
  inviteTitle: 'Convidar o seu grupo',
  inviteSub: 'Envie este link às pessoas que ficam consigo. Cada uma adiciona o seu nome e o anfitrião vê quem entrou.',
  inviteCreating: 'A criar o seu link…',
  inviteShare: 'Partilhar',
  inviteCopy: 'Copiar link',
  inviteCopied: 'Copiado',
  inviteText: 'SMS',
  inviteSpotsOne: 'Resta 1 lugar',
  inviteSpotsMany: 'Restam {count} lugares',
  inviteExpiry: 'O link deixa de funcionar após o check-out.',
  inviteShareMessage: 'Junte-se à nossa estadia em {property}! Informações de chegada, guia da casa, dicas locais e chat com o anfitrião, tudo aqui (válido até {date}).',
  inviteErrGeneric: 'Não foi possível criar o convite. Tente novamente.',
  inviteErrNetwork: 'Não foi possível criar o convite. Verifique a sua ligação.',
  inviteErrFull: 'O convite do seu grupo está completo. Peça ao anfitrião para adicionar mais lugares.',
  inviteErrDisabled: 'O seu anfitrião desativou os convites de grupo.',
  inviteErrEnded: 'Esta estadia terminou e já não pode ser partilhada.',
  inviteErrCopy: 'Não foi possível copiar. Mantenha o link premido para o copiar.',
  close: 'Fechar',
  joinTitle: 'Foi convidado para se juntar à estadia',
  joinSub: 'Aceda ao guia da casa, aos detalhes de check-in, às dicas locais e a um contacto direto com o anfitrião. A seguir, adiciona o seu nome.',
  joinCta: 'Juntar-me à estadia',
  joining: 'A entrar…',
  joinInvalid: 'Este link de convite é inválido, está completo ou expirou. Peça um novo link a quem o enviou ou contacte o seu anfitrião.',
  joinError: 'Algo correu mal. Tente novamente.',
  tryAgain: 'Tentar novamente',
  loading: 'A carregar…',
  doorCodeReply: 'Por sua segurança, os códigos de acesso não são partilhados no chat. Avisei o seu anfitrião, que lhe responderá aqui em breve.',
};

const ptBR: Dict = {
  inviteButton: 'Convide seu grupo',
  inviteTitle: 'Convide seu grupo',
  inviteSub: 'Envie este link para as pessoas que vão ficar com você. Cada uma adiciona o próprio nome, e seu anfitrião vê quem entrou.',
  inviteCreating: 'Criando seu link…',
  inviteShare: 'Compartilhar',
  inviteCopy: 'Copiar link',
  inviteCopied: 'Copiado',
  inviteText: 'SMS',
  inviteSpotsOne: 'Resta 1 vaga',
  inviteSpotsMany: 'Restam {count} vagas',
  inviteExpiry: 'O link para de funcionar depois do check-out.',
  inviteShareMessage: 'Venha para a nossa estadia em {property}! Informações de chegada, guia da casa, dicas locais e chat com o anfitrião, tudo aqui (válido até {date}).',
  inviteErrGeneric: 'Não foi possível criar o convite. Tente novamente.',
  inviteErrNetwork: 'Não foi possível criar o convite. Verifique sua conexão.',
  inviteErrFull: 'O convite do seu grupo está cheio. Peça ao seu anfitrião para adicionar mais vagas.',
  inviteErrDisabled: 'Seu anfitrião desativou os convites de grupo.',
  inviteErrEnded: 'Esta estadia terminou e não pode mais ser compartilhada.',
  inviteErrCopy: 'Não foi possível copiar. Mantenha o link pressionado para copiá-lo.',
  close: 'Fechar',
  joinTitle: 'Você foi convidado para a estadia',
  joinSub: 'Acesse o guia da casa, os detalhes de check-in, dicas locais e um contato direto com seu anfitrião. Em seguida, você adiciona seu nome.',
  joinCta: 'Entrar na estadia',
  joining: 'Entrando…',
  joinInvalid: 'Este link de convite é inválido, está cheio ou expirou. Peça um novo link a quem enviou ou fale com seu anfitrião.',
  joinError: 'Algo deu errado. Tente novamente.',
  tryAgain: 'Tentar novamente',
  loading: 'Carregando…',
  doorCodeReply: 'Para sua segurança, códigos de acesso não são compartilhados no chat. Avisei seu anfitrião, e ele vai responder aqui em breve.',
};

const nl: Dict = {
  inviteButton: 'Nodig je groep uit',
  inviteTitle: 'Nodig je groep uit',
  inviteSub: 'Stuur deze link naar de mensen die met je verblijven. Iedereen vult zijn eigen naam in en je host ziet wie er is aangesloten.',
  inviteCreating: 'Je link wordt gemaakt…',
  inviteShare: 'Delen',
  inviteCopy: 'Link kopiëren',
  inviteCopied: 'Gekopieerd',
  inviteText: 'Sms',
  inviteSpotsOne: 'Nog 1 plek vrij',
  inviteSpotsMany: 'Nog {count} plekken vrij',
  inviteExpiry: 'De link werkt niet meer na het uitchecken.',
  inviteShareMessage: 'Doe mee met ons verblijf in {property}! Check-in-info, de huisgids, lokale tips en de host-chat staan hier (geldig tot {date}).',
  inviteErrGeneric: 'De uitnodiging kon niet worden gemaakt. Probeer het opnieuw.',
  inviteErrNetwork: 'De uitnodiging kon niet worden gemaakt. Controleer je verbinding.',
  inviteErrFull: 'De uitnodiging van je groep is vol. Vraag je host om meer plekken toe te voegen.',
  inviteErrDisabled: 'Je host heeft groepsuitnodigingen uitgeschakeld.',
  inviteErrEnded: 'Dit verblijf is afgelopen en kan niet meer worden gedeeld.',
  inviteErrCopy: 'Kopiëren mislukt. Houd de link ingedrukt om hem te kopiëren.',
  close: 'Sluiten',
  joinTitle: 'Je bent uitgenodigd voor het verblijf',
  joinSub: 'Krijg de huisgids, check-in-details, lokale tips en direct contact met je host. Daarna vul je je naam in.',
  joinCta: 'Doe mee met het verblijf',
  joining: 'Bezig met aansluiten…',
  joinInvalid: 'Deze uitnodigingslink is ongeldig, vol of verlopen. Vraag degene die hem stuurde om een nieuwe link, of neem contact op met je host.',
  joinError: 'Er ging iets mis. Probeer het opnieuw.',
  tryAgain: 'Opnieuw proberen',
  loading: 'Laden…',
  doorCodeReply: 'Voor je veiligheid worden toegangscodes niet in de chat gedeeld. Ik heb je host op de hoogte gebracht; je krijgt hier zo snel mogelijk antwoord.',
};

const zhHans: Dict = {
  inviteButton: '邀请同行人员',
  inviteTitle: '邀请同行人员',
  inviteSub: '把这个链接发给与您同住的人。每个人填写自己的名字，房东可以看到谁已加入。',
  inviteCreating: '正在生成链接…',
  inviteShare: '分享',
  inviteCopy: '复制链接',
  inviteCopied: '已复制',
  inviteText: '短信',
  inviteSpotsOne: '还剩 1 个名额',
  inviteSpotsMany: '还剩 {count} 个名额',
  inviteExpiry: '退房后链接将失效。',
  inviteShareMessage: '来加入我们在{property}的住宿吧！入住信息、房屋指南、本地推荐和房东聊天都在这里（有效期至{date}）。',
  inviteErrGeneric: '无法创建邀请，请重试。',
  inviteErrNetwork: '无法创建邀请，请检查网络连接。',
  inviteErrFull: '您的团体邀请名额已满。请联系房东增加名额。',
  inviteErrDisabled: '房东已关闭团体邀请。',
  inviteErrEnded: '本次住宿已结束，无法再分享。',
  inviteErrCopy: '复制失败。请长按链接进行复制。',
  close: '关闭',
  joinTitle: '您受邀加入本次住宿',
  joinSub: '获取房屋指南、入住详情、本地推荐，并可直接联系房东。下一步请填写您的名字。',
  joinCta: '加入住宿',
  joining: '正在加入…',
  joinInvalid: '此邀请链接无效、名额已满或已过期。请向发送者索取新链接，或联系房东。',
  joinError: '出错了，请重试。',
  tryAgain: '重试',
  loading: '加载中…',
  doorCodeReply: '为了您的安全，门禁密码不会在聊天中分享。我已通知房东，房东会尽快在这里回复您。',
};

const ja: Dict = {
  inviteButton: 'グループを招待',
  inviteTitle: 'グループを招待',
  inviteSub: '一緒に宿泊する人にこのリンクを送ってください。各自が自分の名前を入力し、ホストは誰が参加したか確認できます。',
  inviteCreating: 'リンクを作成中…',
  inviteShare: '共有',
  inviteCopy: 'リンクをコピー',
  inviteCopied: 'コピーしました',
  inviteText: 'SMS',
  inviteSpotsOne: '残り1名',
  inviteSpotsMany: '残り{count}名',
  inviteExpiry: 'リンクはチェックアウト後に無効になります。',
  inviteShareMessage: '{property}での滞在に参加しませんか？チェックイン情報、ハウスガイド、周辺のおすすめ、ホストとのチャットがすべてここにあります（{date}まで有効）。',
  inviteErrGeneric: '招待を作成できませんでした。もう一度お試しください。',
  inviteErrNetwork: '招待を作成できませんでした。接続を確認してください。',
  inviteErrFull: 'グループ招待の枠がいっぱいです。ホストに枠の追加を依頼してください。',
  inviteErrDisabled: 'ホストがグループ招待をオフにしています。',
  inviteErrEnded: 'この滞在は終了したため、共有できません。',
  inviteErrCopy: 'コピーできませんでした。リンクを長押ししてコピーしてください。',
  close: '閉じる',
  joinTitle: '滞在への招待が届いています',
  joinSub: 'ハウスガイド、チェックインの詳細、周辺のおすすめを確認でき、ホストに直接連絡できます。次にお名前を入力します。',
  joinCta: '滞在に参加する',
  joining: '参加しています…',
  joinInvalid: 'この招待リンクは無効か、枠がいっぱいか、期限切れです。送ってくれた人に新しいリンクを頼むか、ホストに連絡してください。',
  joinError: '問題が発生しました。もう一度お試しください。',
  tryAgain: '再試行',
  loading: '読み込み中…',
  doorCodeReply: '安全のため、入室コードはチャットでは共有されません。ホストに連絡しましたので、まもなくここで返信があります。',
};

// Lookup keys are lower-cased BCP-47 codes, matching portal-strings.ts.
export const PARTY_DICTIONARIES: Readonly<Record<string, Dict>> = {
  en,
  es,
  fr,
  de,
  it,
  pt,
  'pt-br': ptBR,
  nl,
  'zh-hans': zhHans,
  ja,
};

export const PARTY_STRING_KEYS: readonly string[] = Object.keys(en);

function pickDict(language: string | null | undefined): Dict {
  if (!language) return en;
  const raw = language.toLowerCase();
  const resolved = resolveLanguage(language)?.code.toLowerCase();
  for (const code of [resolved, raw, raw.split('-')[0]]) {
    if (code && PARTY_DICTIONARIES[code]) return PARTY_DICTIONARIES[code];
  }
  if (/^zh(-(cn|sg|hans))?$/.test(raw)) return zhHans;
  return en;
}

/** Translator for party-invite and door-code strings. Missing keys fall back to English. */
export function partyT(language: string | null | undefined): PortalT {
  const dict = pickDict(language);
  return (key, vars) => {
    let text = dict[key] ?? en[key] ?? key;
    if (vars) {
      for (const [name, value] of Object.entries(vars)) {
        text = text.split(`{${name}}`).join(String(value));
      }
    }
    return text;
  };
}
