// Guest-portal UI translations (party access + i18n pass, 2026-08-28).
//
// Static dictionary for every guest-facing string in the portal chrome: menu
// cards, buttons, dropdowns, chat composer, forms, and the local guide. Zero
// runtime cost — no AI translation call is ever made for UI chrome; the AI is
// only involved for conversation content (concierge replies, host translation),
// which the existing language pipeline already handles.
//
// Coverage: the top STR guest languages. Anything missing falls back to
// English, so shipping a partial locale is always safe and adding the remaining
// picker languages later is append-only.
//
// Pure data + one pure lookup: safe to import from client and server code.

import { resolveLanguage } from './languages';

export type PortalT = (key: string, vars?: Record<string, string | number>) => string;

type Dict = Record<string, string>;

const en: Dict = {
  menu: 'Menu',
  back: 'Back',
  backToMenu: 'Back to menu',
  continue: 'Continue',
  checking: 'Checking…',
  saving: 'Saving…',
  loading: 'Loading…',
  close: 'Close',
  reply: 'Reply',
  cancel: 'Cancel',
  sendMessage: 'Send message',
  themeToLight: 'Switch to light mode',
  themeToDark: 'Switch to dark mode',
  poweredBy: 'Powered by Moche AI',
  codeKicker: 'Guest access',
  codeTitle: 'Welcome to {property}',
  codeSub: 'Enter the 4-digit stay code from your host. Everyone in your party uses the same code — you will get your own concierge next.',
  codeHint: 'No code? Ask your host — it is in your booking message.',
  codeError: 'That code does not match this stay. Check with your host and try again.',
  regKicker: 'One last step',
  regTitle: "Who's joining?",
  regSub: 'Everyone in your party gets their own concierge. Tell us who you are — your answers, chats and requests stay yours.',
  regFirstName: 'First name',
  regLastName: 'Last name',
  regPhone: 'Mobile number (optional)',
  regPhoneHint: 'Only used to text you when your host replies.',
  regSms: 'Text me a neutral alert when my host replies.',
  regSmsNote: 'Message and data rates may apply.',
  regTerms: 'I agree to the guest portal terms and host notification policy.',
  regError: 'Could not save your profile.',
  regSubmit: 'Open my portal',
  menuWelcome: 'Welcome',
  menuWelcomeName: 'Welcome, {name}',
  menuSub: 'How can we help you at {property}?',
  menuHostPreview: 'Host preview — you are seeing the portal as a guest would. Only Ask Questions is live in preview.',
  cardAskTitle: 'Ask Questions',
  cardAskBlurb: 'Instant AI answers about Wi-Fi, check-in, house rules, local tips and more.',
  cardHostTitle: 'Message Host Directly',
  cardHostBlurb: 'Reach your host or property staff — a real person, not the AI.',
  cardMaintTitle: 'Report Service Maintenance',
  cardMaintBlurb: 'Something not working? Troubleshoot with the AI, then file a report to the team.',
  cardExtrasTitle: 'Extras & Amenities',
  cardExtrasBlurb: 'Browse and request add-ons, upgrades and experiences for your stay.',
  askTitle: 'Ask a Question',
  askSub: 'Get property-safe answers. If the concierge is not confident, it will say so and ping your host instead of guessing.',
  askEmpty: 'Choose a card above or ask anything about your stay.',
  askPlaceholder: 'Ask about Wi-Fi, check-in, trash, local places…',
  askError: 'Something went wrong. Please try again.',
  askEscNotice: 'I am not confident I have the right answer, so I have pinged your host. Their reply will appear in Host Chat.',
  askOpenHostChat: 'Open Host Chat',
  askSheetSub: 'Pick a question — or type your own in the chat below.',
  askAppliances: 'Which appliance?',
  askApplianceSearch: 'Search appliances…',
  askApplianceLoad: 'Loading appliances…',
  askApplianceNone: 'No appliances match “{query}”.',
  askApplianceEmpty: 'Your host has not listed any appliances for this property yet. Ping them and they can add them — or just ask your question in the chat and the concierge will escalate it if it does not know.',
  askAppliancePing: 'Ping the host',
  askAppliancePinged: 'Your host has been pinged — their reply will appear in Host Chat.',
  askBackToAppliances: 'Back to all appliances',
  askEmergency: 'If this is an emergency, contact local emergency services first.',
  askTyping: 'The concierge is typing…',
  hostReplyTag: 'Host reply',
  apUse: 'How do I use the {name}?',
  apWhere: 'Where is the {name} located?',
  apOn: 'How do I turn on the {name}?',
  apClean: 'How do I clean or refill the {name}?',
  apBroken: 'The {name} is not working — what should I do?',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'Network and connection help.',
  fbWifiP: 'What is the Wi-Fi network and password?',
  fbWifiQ1: 'What is the Wi-Fi network name?',
  fbWifiQ2: 'What is the Wi-Fi password?',
  fbWifiQ3: 'Where is the Wi-Fi router located?',
  fbWifiQ4: 'The Wi-Fi is not working — what should I try?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Arrival and access instructions.',
  fbCheckinP: 'What are the check-in instructions?',
  fbCheckinQ1: 'What time is check-in?',
  fbCheckinQ2: 'How do I get into the property?',
  fbCheckinQ3: 'Is early check-in possible?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Departure steps and timing.',
  fbCheckoutP: 'What are the check-out instructions?',
  fbCheckoutQ1: 'What time is check-out?',
  fbCheckoutQ2: 'What are the check-out steps?',
  fbCheckoutQ3: 'Is late check-out possible?',
  fbLocalTitle: 'Local recommendations',
  fbLocalDesc: 'Approved places, directions, and links.',
  fbLocalP: 'What local places do you recommend?',
  hostTitle: 'Host Chat',
  hostSub: 'Text your host directly{name}. AI escalations also appear here when the concierge needs a human answer.',
  hostLoading: 'Loading messages…',
  hostEmpty: 'No messages yet. Send a note and your host will reply here.',
  hostPlaceholder: 'Write a message…',
  hostError: 'Could not send your message.',
  hostEscTag: 'AI escalation',
  hostReplyingEsc: 'Replying on this escalation — your answer stays attached to that thread: “{text}”',
  hostReplyingTo: 'Replying to {who}: “{text}”',
  hostWhoHost: 'host',
  hostWhoMessage: 'message',
  hostEscReplies: 'Your host replied to this escalation ({count})',
  hostNote: 'Host replies arrive here; if you opted in, we will also send a neutral text prompt.',
  mTitle: 'Report Maintenance',
  mSub: 'Describe the issue. The AI will first suggest safe things to try, then ask a few quick questions so the team arrives prepared.',
  mPlaceholder: 'e.g. The kitchen sink is leaking under the cabinet…',
  mStart: 'Start report',
  mStarting: 'Starting…',
  mResumeTitle: 'You have a report in progress',
  mResumeCta: 'Continue that report',
  mAnswerPlaceholder: 'Type your answer…',
  mTroubleshooting: 'Troubleshooting',
  mSubmitted: 'Report submitted',
  mHostAlerted: 'Your host has been alerted',
  mRefNumber: 'Reference number',
  mDoneSub: 'Your host and the maintenance team have been notified. Quote the reference number if you follow up.',
  mSafetySub: 'This was treated as urgent and sent to your host right away.',
  mReportAnother: 'Report another issue',
  mError: 'Sorry — something went wrong. Please try again.',
  xTitle: 'Extras & Amenities',
  xEmpty: 'No extras or amenities are available for this stay right now.',
  xYourRequests: 'Your requests',
  xOptions: 'Options',
  xQuantity: 'Quantity',
  xYourName: 'Your name',
  xNamePlaceholder: 'Who should the host expect this from?',
  xWhen: 'Preferred time (optional)',
  xNote: 'Note for the host (optional)',
  xNotePlaceholder: 'Anything we should know?',
  xRequest: 'Request',
  xSending: 'Sending…',
  xSent: 'Request sent',
  xSentSub: 'Your host has been notified and will confirm shortly.',
  xBrowseMore: 'Browse more',
  xRef: 'Reference',
  xErrOption: 'Please choose an option before requesting this.',
  xErrName: 'Please add your name so the host knows who requested this.',
  xNoRequests: 'You have not requested anything yet.',
  xRefPrefix: 'Ref',
  xcatArrival: 'Arrival',
  xcatComfort: 'Comfort',
  xcatFood: 'Food & Drink',
  xcatExperiences: 'Experiences',
  xcatTransport: 'Transport',
  xcatMore: 'More',
  langTitle: 'Language',
  langSub: 'The concierge replies in your language, and your host receives a translation of your messages.',
  langSearch: 'Search languages…',
  langAuto: 'Automatic',
  langAutoSub: 'Match the language I write in',
  langNoMatch: 'No languages match “{query}”.',
  langChoose: 'Choose your language',
  langCurrent: 'Language: {label}',
  lgTitle: 'Local Guide',
  lgSub: 'Restaurants, cafes, parks, golf and more near {property} — with your host\'s own picks first.',
  lgEmpty: 'No local places are listed for this stay yet.',
  lgEmptyHint: 'Ask the concierge in the portal chat — it can recommend area spots and ping your host for their favorites.',
  lgSearch: 'Search places, notes, addresses…',
  lgAll: 'All',
  lgHostPicks: 'Host picks',
  lgMatching: 'Matching places',
  lgMore: 'More nearby',
  lgAllPlaces: 'All places',
  lgNoMatch: 'No places match your search.',
  lgDirections: 'Directions',
  lgWebsite: 'Website',
  lgCall: 'Call',
  lgHostPick: 'Host pick',
  lgHostNote: 'Host note:',
  lgBack: 'Portal',
};

const es: Dict = {
  menu: 'Menú',
  back: 'Atrás',
  backToMenu: 'Volver al menú',
  continue: 'Continuar',
  checking: 'Comprobando…',
  saving: 'Guardando…',
  loading: 'Cargando…',
  close: 'Cerrar',
  reply: 'Responder',
  cancel: 'Cancelar',
  sendMessage: 'Enviar mensaje',
  themeToLight: 'Cambiar a modo claro',
  themeToDark: 'Cambiar a modo oscuro',
  poweredBy: 'Con tecnología de Moche AI',
  codeKicker: 'Acceso de huéspedes',
  codeTitle: 'Bienvenido a {property}',
  codeSub: 'Introduce el código de estancia de 4 dígitos de tu anfitrión. Todos los de tu grupo usan el mismo código — después tendrás tu propio conserje.',
  codeHint: '¿No tienes el código? Pídeselo a tu anfitrión — está en el mensaje de tu reserva.',
  codeError: 'Ese código no coincide con esta estancia. Consulta con tu anfitrión e inténtalo de nuevo.',
  regKicker: 'Un último paso',
  regTitle: '¿Quién se registra?',
  regSub: 'Cada persona de tu grupo tiene su propio conserje. Dinos quién eres — tus respuestas, chats y solicitudes son solo tuyos.',
  regFirstName: 'Nombre',
  regLastName: 'Apellido',
  regPhone: 'Número de móvil (opcional)',
  regPhoneHint: 'Solo se usa para avisarte por SMS cuando responda tu anfitrión.',
  regSms: 'Envíame un SMS neutro cuando mi anfitrión responda.',
  regSmsNote: 'Pueden aplicarse tarifas de mensajes y datos.',
  regTerms: 'Acepto los términos del portal de huéspedes y la política de notificaciones del anfitrión.',
  regError: 'No se pudo guardar tu perfil.',
  regSubmit: 'Abrir mi portal',
  menuWelcome: 'Bienvenido',
  menuWelcomeName: 'Bienvenido, {name}',
  menuSub: '¿Cómo podemos ayudarte en {property}?',
  menuHostPreview: 'Vista previa del anfitrión — ves el portal como lo vería un huésped. Solo Preguntas está activo en la vista previa.',
  cardAskTitle: 'Hacer preguntas',
  cardAskBlurb: 'Respuestas instantáneas de la IA sobre Wi-Fi, check-in, normas de la casa, recomendaciones locales y más.',
  cardHostTitle: 'Escribir al anfitrión',
  cardHostBlurb: 'Contacta con tu anfitrión o el personal de la propiedad — una persona real, no la IA.',
  cardMaintTitle: 'Reportar mantenimiento',
  cardMaintBlurb: '¿Algo no funciona? Resuélvelo con la IA y luego envía un reporte al equipo.',
  cardExtrasTitle: 'Extras y servicios',
  cardExtrasBlurb: 'Explora y solicita complementos, mejoras y experiencias para tu estancia.',
  askTitle: 'Haz una pregunta',
  askSub: 'Respuestas seguras sobre la propiedad. Si el conserje no está seguro, avisa a tu anfitrión en lugar de adivinar.',
  askEmpty: 'Elige una tarjeta arriba o pregunta lo que quieras sobre tu estancia.',
  askPlaceholder: 'Pregunta sobre Wi-Fi, check-in, basura, lugares locales…',
  askError: 'Algo salió mal. Inténtalo de nuevo.',
  askEscNotice: 'No estoy seguro de tener la respuesta correcta, así que he avisado a tu anfitrión. Su respuesta aparecerá en el chat con el anfitrión.',
  askOpenHostChat: 'Abrir chat con el anfitrión',
  askSheetSub: 'Elige una pregunta — o escribe la tuya en el chat.',
  askAppliances: '¿Qué electrodoméstico?',
  askApplianceSearch: 'Buscar electrodomésticos…',
  askApplianceLoad: 'Cargando electrodomésticos…',
  askApplianceNone: 'Ningún electrodoméstico coincide con “{query}”.',
  askApplianceEmpty: 'Tu anfitrión aún no ha registrado electrodomésticos para esta propiedad. Avísale para que los añada — o pregunta en el chat y el conserje lo escalará si no lo sabe.',
  askAppliancePing: 'Avisar al anfitrión',
  askAppliancePinged: 'Tu anfitrión ha sido avisado — su respuesta aparecerá en el chat.',
  askBackToAppliances: 'Volver a todos los electrodomésticos',
  askEmergency: 'Si es una emergencia, contacta primero con los servicios de emergencia locales.',
  askTyping: 'El conserje está escribiendo…',
  hostReplyTag: 'Respuesta del anfitrión',
  apUse: '¿Cómo uso {name}?',
  apWhere: '¿Dónde está {name}?',
  apOn: '¿Cómo enciendo {name}?',
  apClean: '¿Cómo limpio o relleno {name}?',
  apBroken: '{name} no funciona — ¿qué hago?',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'Ayuda con la red y la conexión.',
  fbWifiP: '¿Cuál es la red Wi-Fi y la contraseña?',
  fbWifiQ1: '¿Cuál es el nombre de la red Wi-Fi?',
  fbWifiQ2: '¿Cuál es la contraseña del Wi-Fi?',
  fbWifiQ3: '¿Dónde está el router del Wi-Fi?',
  fbWifiQ4: 'El Wi-Fi no funciona — ¿qué puedo intentar?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Instrucciones de llegada y acceso.',
  fbCheckinP: '¿Cuáles son las instrucciones de check-in?',
  fbCheckinQ1: '¿A qué hora es el check-in?',
  fbCheckinQ2: '¿Cómo entro en la propiedad?',
  fbCheckinQ3: '¿Es posible un check-in anticipado?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Pasos y horario de salida.',
  fbCheckoutP: '¿Cuáles son las instrucciones de check-out?',
  fbCheckoutQ1: '¿A qué hora es el check-out?',
  fbCheckoutQ2: '¿Cuáles son los pasos del check-out?',
  fbCheckoutQ3: '¿Es posible un check-out tardío?',
  fbLocalTitle: 'Recomendaciones locales',
  fbLocalDesc: 'Lugares aprobados, direcciones y enlaces.',
  fbLocalP: '¿Qué lugares locales recomiendas?',
  hostTitle: 'Chat con el anfitrión',
  hostSub: 'Escribe directamente a tu anfitrión{name}. Las escaladas de la IA también aparecen aquí cuando el conserje necesita una respuesta humana.',
  hostLoading: 'Cargando mensajes…',
  hostEmpty: 'Aún no hay mensajes. Envía una nota y tu anfitrión responderá aquí.',
  hostPlaceholder: 'Escribe un mensaje…',
  hostError: 'No se pudo enviar tu mensaje.',
  hostEscTag: 'Escalada de IA',
  hostReplyingEsc: 'Respondiendo a esta escalada — tu respuesta queda en ese hilo: “{text}”',
  hostReplyingTo: 'Respondiendo a {who}: “{text}”',
  hostWhoHost: 'anfitrión',
  hostWhoMessage: 'mensaje',
  hostEscReplies: 'Tu anfitrión respondió a esta escalada ({count})',
  hostNote: 'Las respuestas del anfitrión llegan aquí; si lo activaste, también te enviaremos un SMS neutro.',
  mTitle: 'Reportar mantenimiento',
  mSub: 'Describe el problema. La IA primero sugerirá cosas seguras para probar y luego hará algunas preguntas rápidas para que el equipo llegue preparado.',
  mPlaceholder: 'p. ej., el fregadero de la cocina gotea bajo el mueble…',
  mStart: 'Iniciar reporte',
  mStarting: 'Iniciando…',
  mResumeTitle: 'Tienes un reporte en curso',
  mResumeCta: 'Continuar ese reporte',
  mAnswerPlaceholder: 'Escribe tu respuesta…',
  mTroubleshooting: 'Solución de problemas',
  mSubmitted: 'Reporte enviado',
  mHostAlerted: 'Tu anfitrión ha sido alertado',
  mRefNumber: 'Número de referencia',
  mDoneSub: 'Tu anfitrión y el equipo de mantenimiento han sido notificados. Cita el número de referencia si haces seguimiento.',
  mSafetySub: 'Esto se trató como urgente y se envió a tu anfitrión de inmediato.',
  mReportAnother: 'Reportar otro problema',
  mError: 'Lo siento — algo salió mal. Inténtalo de nuevo.',
  xTitle: 'Extras y servicios',
  xEmpty: 'No hay extras ni servicios disponibles para esta estancia ahora mismo.',
  xYourRequests: 'Tus solicitudes',
  xOptions: 'Opciones',
  xQuantity: 'Cantidad',
  xYourName: 'Tu nombre',
  xNamePlaceholder: '¿De parte de quién debe esperarlo el anfitrión?',
  xWhen: 'Hora preferida (opcional)',
  xNote: 'Nota para el anfitrión (opcional)',
  xNotePlaceholder: '¿Algo que debamos saber?',
  xRequest: 'Solicitar',
  xSending: 'Enviando…',
  xSent: 'Solicitud enviada',
  xSentSub: 'Tu anfitrión ha sido notificado y confirmará en breve.',
  xBrowseMore: 'Ver más',
  xRef: 'Referencia',
  xErrOption: 'Elige una opción antes de solicitarlo.',
  xErrName: 'Añade tu nombre para que el anfitrión sepa quién lo solicita.',
  xNoRequests: 'Aún no has solicitado nada.',
  xRefPrefix: 'Ref',
  xcatArrival: 'Llegada',
  xcatComfort: 'Comodidad',
  xcatFood: 'Comida y bebida',
  xcatExperiences: 'Experiencias',
  xcatTransport: 'Transporte',
  xcatMore: 'Más',
  langTitle: 'Idioma',
  langSub: 'El conserje responde en tu idioma y tu anfitrión recibe una traducción de tus mensajes.',
  langSearch: 'Buscar idiomas…',
  langAuto: 'Automático',
  langAutoSub: 'Usar el idioma en que escribo',
  langNoMatch: 'Ningún idioma coincide con “{query}”.',
  langChoose: 'Elige tu idioma',
  langCurrent: 'Idioma: {label}',
  lgTitle: 'Guía local',
  lgSub: 'Restaurantes, cafés, parques, golf y más cerca de {property} — con las elecciones de tu anfitrión primero.',
  lgEmpty: 'Aún no hay lugares locales registrados para esta estancia.',
  lgEmptyHint: 'Pregunta al conserje en el chat del portal — puede recomendarte lugares de la zona y pedir a tu anfitrión sus favoritos.',
  lgSearch: 'Buscar lugares, notas, direcciones…',
  lgAll: 'Todo',
  lgHostPicks: 'Elecciones del anfitrión',
  lgMatching: 'Lugares coincidentes',
  lgMore: 'Más cerca',
  lgAllPlaces: 'Todos los lugares',
  lgNoMatch: 'Ningún lugar coincide con tu búsqueda.',
  lgDirections: 'Cómo llegar',
  lgWebsite: 'Sitio web',
  lgCall: 'Llamar',
  lgHostPick: 'Elección del anfitrión',
  lgHostNote: 'Nota del anfitrión:',
  lgBack: 'Portal',
};

const fr: Dict = {
  menu: 'Menu',
  back: 'Retour',
  backToMenu: 'Retour au menu',
  continue: 'Continuer',
  checking: 'Vérification…',
  saving: 'Enregistrement…',
  loading: 'Chargement…',
  close: 'Fermer',
  reply: 'Répondre',
  cancel: 'Annuler',
  sendMessage: 'Envoyer le message',
  themeToLight: 'Passer en mode clair',
  themeToDark: 'Passer en mode sombre',
  poweredBy: 'Propulsé par Moche AI',
  codeKicker: 'Accès invité',
  codeTitle: 'Bienvenue à {property}',
  codeSub: 'Saisissez le code de séjour à 4 chiffres fourni par votre hôte. Tout votre groupe utilise le même code — vous aurez ensuite votre propre concierge.',
  codeHint: 'Pas de code ? Demandez à votre hôte — il figure dans le message de votre réservation.',
  codeError: 'Ce code ne correspond pas à ce séjour. Vérifiez auprès de votre hôte et réessayez.',
  regKicker: 'Une dernière étape',
  regTitle: 'Qui nous rejoint ?',
  regSub: 'Chaque membre de votre groupe dispose de son propre concierge. Dites-nous qui vous êtes — vos réponses, discussions et demandes restent à vous.',
  regFirstName: 'Prénom',
  regLastName: 'Nom',
  regPhone: 'Numéro de mobile (facultatif)',
  regPhoneHint: 'Utilisé uniquement pour vous prévenir par SMS quand votre hôte répond.',
  regSms: "M'envoyer un SMS neutre quand mon hôte répond.",
  regSmsNote: 'Des frais de messages et de données peuvent s’appliquer.',
  regTerms: "J'accepte les conditions du portail invité et la politique de notification de l'hôte.",
  regError: "Impossible d'enregistrer votre profil.",
  regSubmit: 'Ouvrir mon portail',
  menuWelcome: 'Bienvenue',
  menuWelcomeName: 'Bienvenue, {name}',
  menuSub: 'Comment pouvons-nous vous aider à {property} ?',
  menuHostPreview: 'Aperçu hôte — vous voyez le portail comme un invité. Seul « Poser une question » est actif dans l’aperçu.',
  cardAskTitle: 'Poser des questions',
  cardAskBlurb: 'Réponses IA instantanées sur le Wi-Fi, l’arrivée, le règlement, les adresses locales et plus.',
  cardHostTitle: 'Écrire directement à l’hôte',
  cardHostBlurb: 'Contactez votre hôte ou le personnel — une vraie personne, pas l’IA.',
  cardMaintTitle: 'Signaler un problème',
  cardMaintBlurb: 'Quelque chose ne marche pas ? Dépannez avec l’IA puis envoyez un rapport à l’équipe.',
  cardExtrasTitle: 'Extras et équipements',
  cardExtrasBlurb: 'Parcourez et demandez des options, surclassements et expériences pour votre séjour.',
  askTitle: 'Poser une question',
  askSub: 'Des réponses fiables sur la propriété. Si le concierge n’est pas sûr, il prévient votre hôte au lieu de deviner.',
  askEmpty: 'Choisissez une carte ci-dessus ou posez une question sur votre séjour.',
  askPlaceholder: 'Wi-Fi, arrivée, poubelles, adresses locales…',
  askError: 'Une erreur est survenue. Veuillez réessayer.',
  askEscNotice: 'Je ne suis pas sûr d’avoir la bonne réponse, j’ai donc prévenu votre hôte. Sa réponse apparaîtra dans le chat hôte.',
  askOpenHostChat: 'Ouvrir le chat hôte',
  askSheetSub: 'Choisissez une question — ou écrivez la vôtre dans le chat.',
  askAppliances: 'Quel appareil ?',
  askApplianceSearch: 'Rechercher un appareil…',
  askApplianceLoad: 'Chargement des appareils…',
  askApplianceNone: 'Aucun appareil ne correspond à « {query} ».',
  askApplianceEmpty: 'Votre hôte n’a pas encore répertorié d’appareils pour cette propriété. Prévenez-le pour qu’il les ajoute — ou posez votre question dans le chat et le concierge la transmettra s’il ne sait pas.',
  askAppliancePing: 'Prévenir l’hôte',
  askAppliancePinged: 'Votre hôte a été prévenu — sa réponse apparaîtra dans le chat.',
  askBackToAppliances: 'Retour à tous les appareils',
  askEmergency: 'En cas d’urgence, contactez d’abord les services d’urgence locaux.',
  askTyping: 'Le concierge est en train d’écrire…',
  hostReplyTag: 'Réponse de l’hôte',
  apUse: 'Comment utiliser {name} ?',
  apWhere: 'Où se trouve {name} ?',
  apOn: 'Comment allumer {name} ?',
  apClean: 'Comment nettoyer ou recharger {name} ?',
  apBroken: '{name} ne fonctionne pas — que faire ?',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'Aide sur le réseau et la connexion.',
  fbWifiP: 'Quel est le réseau Wi-Fi et le mot de passe ?',
  fbWifiQ1: 'Quel est le nom du réseau Wi-Fi ?',
  fbWifiQ2: 'Quel est le mot de passe du Wi-Fi ?',
  fbWifiQ3: 'Où se trouve le routeur Wi-Fi ?',
  fbWifiQ4: 'Le Wi-Fi ne marche pas — que puis-je essayer ?',
  fbCheckinTitle: 'Arrivée',
  fbCheckinDesc: 'Instructions d’arrivée et d’accès.',
  fbCheckinP: 'Quelles sont les instructions d’arrivée ?',
  fbCheckinQ1: 'À quelle heure est l’arrivée ?',
  fbCheckinQ2: 'Comment entrer dans la propriété ?',
  fbCheckinQ3: 'Une arrivée anticipée est-elle possible ?',
  fbCheckoutTitle: 'Départ',
  fbCheckoutDesc: 'Étapes et horaires de départ.',
  fbCheckoutP: 'Quelles sont les instructions de départ ?',
  fbCheckoutQ1: 'À quelle heure est le départ ?',
  fbCheckoutQ2: 'Quelles sont les étapes du départ ?',
  fbCheckoutQ3: 'Un départ tardif est-il possible ?',
  fbLocalTitle: 'Recommandations locales',
  fbLocalDesc: 'Adresses approuvées, itinéraires et liens.',
  fbLocalP: 'Quelles adresses locales recommandez-vous ?',
  hostTitle: 'Chat avec l’hôte',
  hostSub: 'Écrivez directement à votre hôte{name}. Les escalades de l’IA apparaissent aussi ici quand le concierge a besoin d’un humain.',
  hostLoading: 'Chargement des messages…',
  hostEmpty: 'Pas encore de messages. Envoyez un mot et votre hôte répondra ici.',
  hostPlaceholder: 'Écrivez un message…',
  hostError: 'Impossible d’envoyer votre message.',
  hostEscTag: 'Escalade IA',
  hostReplyingEsc: 'Vous répondez à cette escalade — votre réponse reste dans ce fil : « {text} »',
  hostReplyingTo: 'Réponse à {who} : « {text} »',
  hostWhoHost: 'l’hôte',
  hostWhoMessage: 'le message',
  hostEscReplies: 'Votre hôte a répondu à cette escalade ({count})',
  hostNote: 'Les réponses de l’hôte arrivent ici ; si vous l’avez activé, nous envoyons aussi un SMS neutre.',
  mTitle: 'Signaler un problème',
  mSub: 'Décrivez le problème. L’IA suggérera d’abord des gestes sûrs, puis posera quelques questions rapides pour que l’équipe arrive préparée.',
  mPlaceholder: 'ex. : l’évier de la cuisine fuit sous le meuble…',
  mStart: 'Créer le rapport',
  mStarting: 'Création…',
  mResumeTitle: 'Vous avez un rapport en cours',
  mResumeCta: 'Reprendre ce rapport',
  mAnswerPlaceholder: 'Écrivez votre réponse…',
  mTroubleshooting: 'Dépannage',
  mSubmitted: 'Rapport envoyé',
  mHostAlerted: 'Votre hôte a été alerté',
  mRefNumber: 'Numéro de référence',
  mDoneSub: 'Votre hôte et l’équipe de maintenance ont été prévenus. Citez le numéro de référence en cas de suivi.',
  mSafetySub: 'Cela a été traité comme urgent et envoyé immédiatement à votre hôte.',
  mReportAnother: 'Signaler un autre problème',
  mError: 'Désolé — une erreur est survenue. Réessayez.',
  xTitle: 'Extras et équipements',
  xEmpty: 'Aucun extra ni équipement n’est disponible pour ce séjour pour le moment.',
  xYourRequests: 'Vos demandes',
  xOptions: 'Options',
  xQuantity: 'Quantité',
  xYourName: 'Votre nom',
  xNamePlaceholder: 'De la part de qui l’hôte doit-il l’attendre ?',
  xWhen: 'Heure souhaitée (facultatif)',
  xNote: 'Note pour l’hôte (facultatif)',
  xNotePlaceholder: 'Quelque chose à savoir ?',
  xRequest: 'Demander',
  xSending: 'Envoi…',
  xSent: 'Demande envoyée',
  xSentSub: 'Votre hôte a été prévenu et confirmera bientôt.',
  xBrowseMore: 'Voir plus',
  xRef: 'Référence',
  xErrOption: 'Choisissez une option avant de faire la demande.',
  xErrName: 'Ajoutez votre nom pour que l’hôte sache qui en fait la demande.',
  xNoRequests: 'Vous n’avez encore rien demandé.',
  xRefPrefix: 'Réf',
  xcatArrival: 'Arrivée',
  xcatComfort: 'Confort',
  xcatFood: 'Cuisine et boissons',
  xcatExperiences: 'Expériences',
  xcatTransport: 'Transport',
  xcatMore: 'Plus',
  langTitle: 'Langue',
  langSub: 'Le concierge répond dans votre langue et votre hôte reçoit une traduction de vos messages.',
  langSearch: 'Rechercher une langue…',
  langAuto: 'Automatique',
  langAutoSub: 'Utiliser la langue dans laquelle j’écris',
  langNoMatch: 'Aucune langue ne correspond à « {query} ».',
  langChoose: 'Choisissez votre langue',
  langCurrent: 'Langue : {label}',
  lgTitle: 'Guide local',
  lgSub: 'Restaurants, cafés, parcs, golf et plus près de {property} — avec les coups de cœur de votre hôte d’abord.',
  lgEmpty: 'Aucune adresse locale n’est encore répertoriée pour ce séjour.',
  lgEmptyHint: 'Demandez au concierge dans le chat du portail — il peut recommander des adresses et demander à votre hôte ses favoris.',
  lgSearch: 'Rechercher lieux, notes, adresses…',
  lgAll: 'Tout',
  lgHostPicks: 'Coups de cœur de l’hôte',
  lgMatching: 'Lieux correspondants',
  lgMore: 'Plus à proximité',
  lgAllPlaces: 'Tous les lieux',
  lgNoMatch: 'Aucun lieu ne correspond à votre recherche.',
  lgDirections: 'Itinéraire',
  lgWebsite: 'Site web',
  lgCall: 'Appeler',
  lgHostPick: 'Coup de cœur de l’hôte',
  lgHostNote: 'Note de l’hôte :',
  lgBack: 'Portail',
};

const de: Dict = {
  menu: 'Menü',
  back: 'Zurück',
  backToMenu: 'Zurück zum Menü',
  continue: 'Weiter',
  checking: 'Wird geprüft…',
  saving: 'Wird gespeichert…',
  loading: 'Wird geladen…',
  close: 'Schließen',
  reply: 'Antworten',
  cancel: 'Abbrechen',
  sendMessage: 'Nachricht senden',
  themeToLight: 'Zum hellen Modus wechseln',
  themeToDark: 'Zum dunklen Modus wechseln',
  poweredBy: 'Bereitgestellt von Moche AI',
  codeKicker: 'Gästezugang',
  codeTitle: 'Willkommen in {property}',
  codeSub: 'Gib den 4-stelligen Aufenthaltscode deines Gastgebers ein. Alle in deiner Gruppe nutzen denselben Code — danach erhältst du deinen eigenen Concierge.',
  codeHint: 'Kein Code? Frag deinen Gastgeber — er steht in deiner Buchungsnachricht.',
  codeError: 'Dieser Code passt nicht zu diesem Aufenthalt. Bitte prüfe ihn mit deinem Gastgeber und versuche es erneut.',
  regKicker: 'Ein letzter Schritt',
  regTitle: 'Wer checkt ein?',
  regSub: 'Jede Person in deiner Gruppe bekommt ihren eigenen Concierge. Sag uns, wer du bist — deine Antworten, Chats und Anfragen bleiben deine.',
  regFirstName: 'Vorname',
  regLastName: 'Nachname',
  regPhone: 'Handynummer (optional)',
  regPhoneHint: 'Wird nur genutzt, um dich per SMS zu benachrichtigen, wenn dein Gastgeber antwortet.',
  regSms: 'Schick mir eine neutrale SMS, wenn mein Gastgeber antwortet.',
  regSmsNote: 'Es können Gebühren für Nachrichten und Daten anfallen.',
  regTerms: 'Ich akzeptiere die Bedingungen des Gästeportals und die Benachrichtigungsrichtlinie des Gastgebers.',
  regError: 'Dein Profil konnte nicht gespeichert werden.',
  regSubmit: 'Mein Portal öffnen',
  menuWelcome: 'Willkommen',
  menuWelcomeName: 'Willkommen, {name}',
  menuSub: 'Wie können wir dir in {property} helfen?',
  menuHostPreview: 'Gastgeber-Vorschau — du siehst das Portal wie ein Gast. Nur „Fragen stellen“ ist in der Vorschau aktiv.',
  cardAskTitle: 'Fragen stellen',
  cardAskBlurb: 'Sofortige KI-Antworten zu WLAN, Check-in, Hausregeln, lokalen Tipps und mehr.',
  cardHostTitle: 'Gastgeber direkt anschreiben',
  cardHostBlurb: 'Erreiche deinen Gastgeber oder das Team — ein echter Mensch, nicht die KI.',
  cardMaintTitle: 'Wartung melden',
  cardMaintBlurb: 'Etwas funktioniert nicht? Löse es mit der KI und sende dann einen Bericht ans Team.',
  cardExtrasTitle: 'Extras & Annehmlichkeiten',
  cardExtrasBlurb: 'Stöbere und fordere Extras, Upgrades und Erlebnisse für deinen Aufenthalt an.',
  askTitle: 'Eine Frage stellen',
  askSub: 'Verlässliche Antworten zur Unterkunft. Wenn der Concierge unsicher ist, benachrichtigt er deinen Gastgeber, statt zu raten.',
  askEmpty: 'Wähle oben eine Karte oder frag alles zu deinem Aufenthalt.',
  askPlaceholder: 'Frag zu WLAN, Check-in, Müll, Orten in der Nähe…',
  askError: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
  askEscNotice: 'Ich bin nicht sicher, ob ich die richtige Antwort habe, also habe ich deinen Gastgeber benachrichtigt. Seine Antwort erscheint im Gastgeber-Chat.',
  askOpenHostChat: 'Gastgeber-Chat öffnen',
  askSheetSub: 'Wähle eine Frage — oder tippe deine eigene im Chat.',
  askAppliances: 'Welches Gerät?',
  askApplianceSearch: 'Geräte suchen…',
  askApplianceLoad: 'Geräte werden geladen…',
  askApplianceNone: 'Keine Geräte passen zu „{query}“.',
  askApplianceEmpty: 'Dein Gastgeber hat für diese Unterkunft noch keine Geräte hinterlegt. Benachrichtige ihn, damit er sie hinzufügt — oder frag einfach im Chat und der Concierge leitet es weiter, falls er es nicht weiß.',
  askAppliancePing: 'Gastgeber benachrichtigen',
  askAppliancePinged: 'Dein Gastgeber wurde benachrichtigt — seine Antwort erscheint im Chat.',
  askBackToAppliances: 'Zurück zu allen Geräten',
  askEmergency: 'Wende dich im Notfall zuerst an die örtlichen Notdienste.',
  askTyping: 'Der Concierge schreibt…',
  hostReplyTag: 'Antwort des Gastgebers',
  apUse: 'Wie benutze ich {name}?',
  apWhere: 'Wo befindet sich {name}?',
  apOn: 'Wie schalte ich {name} ein?',
  apClean: 'Wie reinige oder fülle ich {name}?',
  apBroken: '{name} funktioniert nicht — was soll ich tun?',
  fbWifiTitle: 'WLAN',
  fbWifiDesc: 'Hilfe zu Netzwerk und Verbindung.',
  fbWifiP: 'Wie lauten WLAN-Name und Passwort?',
  fbWifiQ1: 'Wie heißt das WLAN-Netzwerk?',
  fbWifiQ2: 'Wie lautet das WLAN-Passwort?',
  fbWifiQ3: 'Wo ist der WLAN-Router?',
  fbWifiQ4: 'Das WLAN funktioniert nicht — was kann ich versuchen?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Anreise- und Zugangshinweise.',
  fbCheckinP: 'Wie lauten die Check-in-Hinweise?',
  fbCheckinQ1: 'Wann ist der Check-in?',
  fbCheckinQ2: 'Wie komme ich in die Unterkunft?',
  fbCheckinQ3: 'Ist ein früher Check-in möglich?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Schritte und Zeiten für die Abreise.',
  fbCheckoutP: 'Wie lauten die Check-out-Hinweise?',
  fbCheckoutQ1: 'Wann ist der Check-out?',
  fbCheckoutQ2: 'Was sind die Check-out-Schritte?',
  fbCheckoutQ3: 'Ist ein später Check-out möglich?',
  fbLocalTitle: 'Lokale Empfehlungen',
  fbLocalDesc: 'Geprüfte Orte, Wegbeschreibungen und Links.',
  fbLocalP: 'Welche Orte in der Nähe empfiehlst du?',
  hostTitle: 'Gastgeber-Chat',
  hostSub: 'Schreib deinem Gastgeber direkt{name}. KI-Eskalationen erscheinen ebenfalls hier, wenn der Concierge eine menschliche Antwort braucht.',
  hostLoading: 'Nachrichten werden geladen…',
  hostEmpty: 'Noch keine Nachrichten. Schreib eine kurze Nachricht und dein Gastgeber antwortet hier.',
  hostPlaceholder: 'Nachricht schreiben…',
  hostError: 'Deine Nachricht konnte nicht gesendet werden.',
  hostEscTag: 'KI-Eskalation',
  hostReplyingEsc: 'Du antwortest auf diese Eskalation — deine Antwort bleibt in diesem Verlauf: „{text}“',
  hostReplyingTo: 'Antwort an {who}: „{text}“',
  hostWhoHost: 'Gastgeber',
  hostWhoMessage: 'Nachricht',
  hostEscReplies: 'Dein Gastgeber hat auf diese Eskalation geantwortet ({count})',
  hostNote: 'Antworten des Gastgebers kommen hier an; falls aktiviert, senden wir zusätzlich eine neutrale SMS.',
  mTitle: 'Wartung melden',
  mSub: 'Beschreibe das Problem. Die KI schlägt zuerst sichere Lösungen vor und stellt dann ein paar kurze Fragen, damit das Team vorbereitet ankommt.',
  mPlaceholder: 'z. B. Die Küchenspüle tropft unter dem Unterschrank…',
  mStart: 'Bericht starten',
  mStarting: 'Wird gestartet…',
  mResumeTitle: 'Du hast einen laufenden Bericht',
  mResumeCta: 'Diesen Bericht fortsetzen',
  mAnswerPlaceholder: 'Tippe deine Antwort…',
  mTroubleshooting: 'Fehlersuche',
  mSubmitted: 'Bericht gesendet',
  mHostAlerted: 'Dein Gastgeber wurde benachrichtigt',
  mRefNumber: 'Referenznummer',
  mDoneSub: 'Dein Gastgeber und das Wartungsteam wurden benachrichtigt. Nenne bei Rückfragen die Referenznummer.',
  mSafetySub: 'Dies wurde als dringend behandelt und sofort an deinen Gastgeber gesendet.',
  mReportAnother: 'Anderes Problem melden',
  mError: 'Entschuldigung — etwas ist schiefgelaufen. Bitte versuche es erneut.',
  xTitle: 'Extras & Annehmlichkeiten',
  xEmpty: 'Für diesen Aufenthalt sind derzeit keine Extras oder Annehmlichkeiten verfügbar.',
  xYourRequests: 'Deine Anfragen',
  xOptions: 'Optionen',
  xQuantity: 'Anzahl',
  xYourName: 'Dein Name',
  xNamePlaceholder: 'Von wem soll der Gastgeber dies erwarten?',
  xWhen: 'Wunschzeit (optional)',
  xNote: 'Notiz an den Gastgeber (optional)',
  xNotePlaceholder: 'Etwas, das wir wissen sollten?',
  xRequest: 'Anfragen',
  xSending: 'Wird gesendet…',
  xSent: 'Anfrage gesendet',
  xSentSub: 'Dein Gastgeber wurde benachrichtigt und bestätigt in Kürze.',
  xBrowseMore: 'Weiter stöbern',
  xRef: 'Referenz',
  xErrOption: 'Bitte wähle vor der Anfrage eine Option.',
  xErrName: 'Bitte füge deinen Namen hinzu, damit der Gastgeber weiß, von wem die Anfrage kommt.',
  xNoRequests: 'Du hast noch nichts angefragt.',
  xRefPrefix: 'Ref',
  xcatArrival: 'Anreise',
  xcatComfort: 'Komfort',
  xcatFood: 'Essen & Trinken',
  xcatExperiences: 'Erlebnisse',
  xcatTransport: 'Transport',
  xcatMore: 'Mehr',
  langTitle: 'Sprache',
  langSub: 'Der Concierge antwortet in deiner Sprache und dein Gastgeber erhält eine Übersetzung deiner Nachrichten.',
  langSearch: 'Sprachen suchen…',
  langAuto: 'Automatisch',
  langAutoSub: 'Die Sprache nutzen, in der ich schreibe',
  langNoMatch: 'Keine Sprachen passen zu „{query}“.',
  langChoose: 'Wähle deine Sprache',
  langCurrent: 'Sprache: {label}',
  lgTitle: 'Lokaler Guide',
  lgSub: 'Restaurants, Cafés, Parks, Golf und mehr in der Nähe von {property} — mit den Tipps deines Gastgebers zuerst.',
  lgEmpty: 'Für diesen Aufenthalt sind noch keine Orte hinterlegt.',
  lgEmptyHint: 'Frag den Concierge im Portal-Chat — er kann Orte in der Nähe empfehlen und deinen Gastgeber nach seinen Favoriten fragen.',
  lgSearch: 'Orte, Notizen, Adressen suchen…',
  lgAll: 'Alle',
  lgHostPicks: 'Tipps des Gastgebers',
  lgMatching: 'Passende Orte',
  lgMore: 'Mehr in der Nähe',
  lgAllPlaces: 'Alle Orte',
  lgNoMatch: 'Keine Orte passen zu deiner Suche.',
  lgDirections: 'Route',
  lgWebsite: 'Webseite',
  lgCall: 'Anrufen',
  lgHostPick: 'Tipp des Gastgebers',
  lgHostNote: 'Notiz des Gastgebers:',
  lgBack: 'Portal',
};

const it: Dict = {
  menu: 'Menu',
  back: 'Indietro',
  backToMenu: 'Torna al menu',
  continue: 'Continua',
  checking: 'Verifica in corso…',
  saving: 'Salvataggio…',
  loading: 'Caricamento…',
  close: 'Chiudi',
  reply: 'Rispondi',
  cancel: 'Annulla',
  sendMessage: 'Invia messaggio',
  themeToLight: 'Passa alla modalità chiara',
  themeToDark: 'Passa alla modalità scura',
  poweredBy: 'Offerto da Moche AI',
  codeKicker: 'Accesso ospiti',
  codeTitle: 'Benvenuto a {property}',
  codeSub: 'Inserisci il codice soggiorno di 4 cifre fornito dal tuo host. Tutto il tuo gruppo usa lo stesso codice — poi avrai il tuo concierge personale.',
  codeHint: 'Non hai il codice? Chiedilo al tuo host — è nel messaggio della prenotazione.',
  codeError: 'Questo codice non corrisponde a questo soggiorno. Verifica con il tuo host e riprova.',
  regKicker: 'Un ultimo passo',
  regTitle: 'Chi sei?',
  regSub: 'Ogni persona del gruppo ha il proprio concierge. Dicci chi sei — le tue risposte, chat e richieste restano tue.',
  regFirstName: 'Nome',
  regLastName: 'Cognome',
  regPhone: 'Numero di cellulare (facoltativo)',
  regPhoneHint: 'Usato solo per avvisarti via SMS quando l’host risponde.',
  regSms: 'Inviami un SMS neutro quando il mio host risponde.',
  regSmsNote: 'Potrebbero applicarsi costi per messaggi e dati.',
  regTerms: 'Accetto i termini del portale ospiti e la politica di notifica dell’host.',
  regError: 'Impossibile salvare il tuo profilo.',
  regSubmit: 'Apri il mio portale',
  menuWelcome: 'Benvenuto',
  menuWelcomeName: 'Benvenuto, {name}',
  menuSub: 'Come possiamo aiutarti a {property}?',
  menuHostPreview: 'Anteprima host — stai vedendo il portale come un ospite. Solo «Fai domande» è attivo nell’anteprima.',
  cardAskTitle: 'Fai domande',
  cardAskBlurb: 'Risposte IA immediate su Wi-Fi, check-in, regole della casa, consigli locali e altro.',
  cardHostTitle: 'Scrivi direttamente all’host',
  cardHostBlurb: 'Contatta l’host o lo staff della struttura — una persona vera, non l’IA.',
  cardMaintTitle: 'Segnala manutenzione',
  cardMaintBlurb: 'Qualcosa non funziona? Risolvi con l’IA e poi invia una segnalazione al team.',
  cardExtrasTitle: 'Extra e servizi',
  cardExtrasBlurb: 'Sfoglia e richiedi aggiunte, upgrade ed esperienze per il tuo soggiorno.',
  askTitle: 'Fai una domanda',
  askSub: 'Risposte affidabili sulla struttura. Se il concierge non è sicuro, avvisa il tuo host invece di tirare a indovinare.',
  askEmpty: 'Scegli una scheda qui sopra o chiedi qualsiasi cosa sul tuo soggiorno.',
  askPlaceholder: 'Chiedi di Wi-Fi, check-in, spazzatura, posti locali…',
  askError: 'Qualcosa è andato storto. Riprova.',
  askEscNotice: 'Non sono sicuro di avere la risposta giusta, quindi ho avvisato il tuo host. La sua risposta apparirà nella chat con l’host.',
  askOpenHostChat: 'Apri la chat con l’host',
  askSheetSub: 'Scegli una domanda — o scrivi la tua nella chat.',
  askAppliances: 'Quale elettrodomestico?',
  askApplianceSearch: 'Cerca elettrodomestici…',
  askApplianceLoad: 'Caricamento elettrodomestici…',
  askApplianceNone: 'Nessun elettrodomestico corrisponde a “{query}”.',
  askApplianceEmpty: 'Il tuo host non ha ancora registrato elettrodomestici per questa struttura. Avvisalo così li aggiunge — oppure chiedi in chat e il concierge lo inoltrerà se non sa.',
  askAppliancePing: 'Avvisa l’host',
  askAppliancePinged: 'Il tuo host è stato avvisato — la sua risposta apparirà nella chat.',
  askBackToAppliances: 'Torna a tutti gli elettrodomestici',
  askEmergency: 'In caso di emergenza, contatta prima i servizi di emergenza locali.',
  askTyping: 'Il concierge sta scrivendo…',
  hostReplyTag: 'Risposta dell’host',
  apUse: 'Come si usa {name}?',
  apWhere: 'Dove si trova {name}?',
  apOn: 'Come si accende {name}?',
  apClean: 'Come si pulisce o si ricarica {name}?',
  apBroken: '{name} non funziona — cosa devo fare?',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'Aiuto su rete e connessione.',
  fbWifiP: 'Qual è la rete Wi-Fi e la password?',
  fbWifiQ1: 'Qual è il nome della rete Wi-Fi?',
  fbWifiQ2: 'Qual è la password del Wi-Fi?',
  fbWifiQ3: 'Dove si trova il router Wi-Fi?',
  fbWifiQ4: 'Il Wi-Fi non funziona — cosa posso provare?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Istruzioni per l’arrivo e l’accesso.',
  fbCheckinP: 'Quali sono le istruzioni per il check-in?',
  fbCheckinQ1: 'A che ora è il check-in?',
  fbCheckinQ2: 'Come entro nella struttura?',
  fbCheckinQ3: 'È possibile un check-in anticipato?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Passaggi e orari di partenza.',
  fbCheckoutP: 'Quali sono le istruzioni per il check-out?',
  fbCheckoutQ1: 'A che ora è il check-out?',
  fbCheckoutQ2: 'Quali sono i passaggi del check-out?',
  fbCheckoutQ3: 'È possibile un check-out posticipato?',
  fbLocalTitle: 'Consigli locali',
  fbLocalDesc: 'Luoghi approvati, indicazioni e link.',
  fbLocalP: 'Quali luoghi locali consigli?',
  hostTitle: 'Chat con l’host',
  hostSub: 'Scrivi direttamente al tuo host{name}. Le escalation dell’IA appaiono qui quando il concierge ha bisogno di una risposta umana.',
  hostLoading: 'Caricamento messaggi…',
  hostEmpty: 'Nessun messaggio. Invia una nota e il tuo host risponderà qui.',
  hostPlaceholder: 'Scrivi un messaggio…',
  hostError: 'Impossibile inviare il messaggio.',
  hostEscTag: 'Escalation IA',
  hostReplyingEsc: 'Stai rispondendo a questa escalation — la risposta resta in quel thread: “{text}”',
  hostReplyingTo: 'Risposta a {who}: “{text}”',
  hostWhoHost: 'host',
  hostWhoMessage: 'messaggio',
  hostEscReplies: 'Il tuo host ha risposto a questa escalation ({count})',
  hostNote: 'Le risposte dell’host arrivano qui; se l’hai attivato, inviamo anche un SMS neutro.',
  mTitle: 'Segnala manutenzione',
  mSub: 'Descrivi il problema. L’IA suggerirà prima soluzioni sicure, poi farà alcune domande rapide perché il team arrivi preparato.',
  mPlaceholder: 'es. il lavandino della cucina perde sotto il mobile…',
  mStart: 'Avvia segnalazione',
  mStarting: 'Avvio in corso…',
  mResumeTitle: 'Hai una segnalazione in corso',
  mResumeCta: 'Continua quella segnalazione',
  mAnswerPlaceholder: 'Scrivi la tua risposta…',
  mTroubleshooting: 'Risoluzione problemi',
  mSubmitted: 'Segnalazione inviata',
  mHostAlerted: 'Il tuo host è stato avvisato',
  mRefNumber: 'Numero di riferimento',
  mDoneSub: 'Il tuo host e il team di manutenzione sono stati avvisati. Cita il numero di riferimento per i follow-up.',
  mSafetySub: 'È stato trattato come urgente e inviato subito al tuo host.',
  mReportAnother: 'Segnala un altro problema',
  mError: 'Spiacente — qualcosa è andato storto. Riprova.',
  xTitle: 'Extra e servizi',
  xEmpty: 'Nessun extra o servizio disponibile per questo soggiorno al momento.',
  xYourRequests: 'Le tue richieste',
  xOptions: 'Opzioni',
  xQuantity: 'Quantità',
  xYourName: 'Il tuo nome',
  xNamePlaceholder: 'Da parte di chi deve aspettarselo l’host?',
  xWhen: 'Orario preferito (facoltativo)',
  xNote: 'Nota per l’host (facoltativa)',
  xNotePlaceholder: 'Qualcosa che dovremmo sapere?',
  xRequest: 'Richiedi',
  xSending: 'Invio in corso…',
  xSent: 'Richiesta inviata',
  xSentSub: 'Il tuo host è stato avvisato e confermerà a breve.',
  xBrowseMore: 'Sfoglia altro',
  xRef: 'Riferimento',
  xErrOption: 'Scegli un’opzione prima di richiederlo.',
  xErrName: 'Aggiungi il tuo nome così l’host sa chi fa la richiesta.',
  xNoRequests: 'Non hai ancora richiesto nulla.',
  xRefPrefix: 'Rif',
  xcatArrival: 'Arrivo',
  xcatComfort: 'Comfort',
  xcatFood: 'Cibo e bevande',
  xcatExperiences: 'Esperienze',
  xcatTransport: 'Trasporti',
  xcatMore: 'Altro',
  langTitle: 'Lingua',
  langSub: 'Il concierge risponde nella tua lingua e il tuo host riceve una traduzione dei tuoi messaggi.',
  langSearch: 'Cerca lingue…',
  langAuto: 'Automatica',
  langAutoSub: 'Usa la lingua in cui scrivo',
  langNoMatch: 'Nessuna lingua corrisponde a “{query}”.',
  langChoose: 'Scegli la tua lingua',
  langCurrent: 'Lingua: {label}',
  lgTitle: 'Guida locale',
  lgSub: 'Ristoranti, caffè, parchi, golf e altro vicino a {property} — con i preferiti del tuo host in cima.',
  lgEmpty: 'Nessun luogo locale è ancora elencato per questo soggiorno.',
  lgEmptyHint: 'Chiedi al concierge nella chat del portale — può consigliare posti in zona e chiedere al tuo host i suoi preferiti.',
  lgSearch: 'Cerca luoghi, note, indirizzi…',
  lgAll: 'Tutto',
  lgHostPicks: 'Preferiti dell’host',
  lgMatching: 'Luoghi corrispondenti',
  lgMore: 'Altro nelle vicinanze',
  lgAllPlaces: 'Tutti i luoghi',
  lgNoMatch: 'Nessun luogo corrisponde alla ricerca.',
  lgDirections: 'Indicazioni',
  lgWebsite: 'Sito web',
  lgCall: 'Chiama',
  lgHostPick: 'Scelta dell’host',
  lgHostNote: 'Nota dell’host:',
  lgBack: 'Portale',
};

const pt: Dict = {
  menu: 'Menu',
  back: 'Voltar',
  backToMenu: 'Voltar ao menu',
  continue: 'Continuar',
  checking: 'A verificar…',
  saving: 'A guardar…',
  loading: 'A carregar…',
  close: 'Fechar',
  reply: 'Responder',
  cancel: 'Cancelar',
  sendMessage: 'Enviar mensagem',
  themeToLight: 'Mudar para o modo claro',
  themeToDark: 'Mudar para o modo escuro',
  poweredBy: 'Com tecnologia Moche AI',
  codeKicker: 'Acesso de hóspedes',
  codeTitle: 'Bem-vindo a {property}',
  codeSub: 'Introduza o código de estadia de 4 dígitos do seu anfitrião. Todos no grupo usam o mesmo código — de seguida terá o seu próprio concierge.',
  codeHint: 'Não tem o código? Pergunte ao seu anfitrião — está na mensagem da reserva.',
  codeError: 'Esse código não corresponde a esta estadia. Confirme com o seu anfitrião e tente novamente.',
  regKicker: 'Um último passo',
  regTitle: 'Quem está a entrar?',
  regSub: 'Cada pessoa do grupo tem o seu próprio concierge. Diga-nos quem é — as suas respostas, conversas e pedidos ficam consigo.',
  regFirstName: 'Nome próprio',
  regLastName: 'Apelido',
  regPhone: 'Número de telemóvel (opcional)',
  regPhoneHint: 'Usado apenas para o avisar por SMS quando o anfitrião responder.',
  regSms: 'Enviem-me um SMS neutro quando o meu anfitrião responder.',
  regSmsNote: 'Podem aplicar-se tarifas de mensagens e dados.',
  regTerms: 'Aceito os termos do portal de hóspedes e a política de notificações do anfitrião.',
  regError: 'Não foi possível guardar o seu perfil.',
  regSubmit: 'Abrir o meu portal',
  menuWelcome: 'Bem-vindo',
  menuWelcomeName: 'Bem-vindo, {name}',
  menuSub: 'Como podemos ajudar em {property}?',
  menuHostPreview: 'Pré-visualização do anfitrião — está a ver o portal como um hóspede. Apenas «Fazer perguntas» está ativo na pré-visualização.',
  cardAskTitle: 'Fazer perguntas',
  cardAskBlurb: 'Respostas instantâneas da IA sobre Wi-Fi, check-in, regras da casa, dicas locais e mais.',
  cardHostTitle: 'Falar diretamente com o anfitrião',
  cardHostBlurb: 'Contacte o seu anfitrião ou a equipa da propriedade — uma pessoa real, não a IA.',
  cardMaintTitle: 'Reportar manutenção',
  cardMaintBlurb: 'Algo não funciona? Resolva com a IA e depois envie um relatório à equipa.',
  cardExtrasTitle: 'Extras e comodidades',
  cardExtrasBlurb: 'Explore e peça extras, upgrades e experiências para a sua estadia.',
  askTitle: 'Faça uma pergunta',
  askSub: 'Respostas fiáveis sobre a propriedade. Se o concierge não tiver a certeza, avisa o seu anfitrião em vez de adivinhar.',
  askEmpty: 'Escolha um cartão acima ou pergunte qualquer coisa sobre a sua estadia.',
  askPlaceholder: 'Pergunte sobre Wi-Fi, check-in, lixo, locais próximos…',
  askError: 'Algo correu mal. Tente novamente.',
  askEscNotice: 'Não tenho a certeza da resposta, por isso avisei o seu anfitrião. A resposta dele aparecerá no chat do anfitrião.',
  askOpenHostChat: 'Abrir chat do anfitrião',
  askSheetSub: 'Escolha uma pergunta — ou escreva a sua no chat.',
  askAppliances: 'Qual eletrodoméstico?',
  askApplianceSearch: 'Procurar eletrodomésticos…',
  askApplianceLoad: 'A carregar eletrodomésticos…',
  askApplianceNone: 'Nenhum eletrodoméstico corresponde a “{query}”.',
  askApplianceEmpty: 'O seu anfitrião ainda não registou eletrodomésticos para esta propriedade. Avise-o para os adicionar — ou pergunte no chat e o concierge encaminha se não souber.',
  askAppliancePing: 'Avisar o anfitrião',
  askAppliancePinged: 'O seu anfitrião foi avisado — a resposta dele aparecerá no chat.',
  askBackToAppliances: 'Voltar a todos os eletrodomésticos',
  askEmergency: 'Em caso de emergência, contacte primeiro os serviços de emergência locais.',
  askTyping: 'O concierge está a escrever…',
  hostReplyTag: 'Resposta do anfitrião',
  apUse: 'Como uso {name}?',
  apWhere: 'Onde fica {name}?',
  apOn: 'Como ligo {name}?',
  apClean: 'Como limpo ou reabasteço {name}?',
  apBroken: '{name} não funciona — o que faço?',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'Ajuda com a rede e a ligação.',
  fbWifiP: 'Qual é a rede Wi-Fi e a palavra-passe?',
  fbWifiQ1: 'Qual é o nome da rede Wi-Fi?',
  fbWifiQ2: 'Qual é a palavra-passe do Wi-Fi?',
  fbWifiQ3: 'Onde está o router do Wi-Fi?',
  fbWifiQ4: 'O Wi-Fi não funciona — o que posso tentar?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Instruções de chegada e acesso.',
  fbCheckinP: 'Quais são as instruções de check-in?',
  fbCheckinQ1: 'A que horas é o check-in?',
  fbCheckinQ2: 'Como entro na propriedade?',
  fbCheckinQ3: 'É possível um check-in antecipado?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Passos e horários de saída.',
  fbCheckoutP: 'Quais são as instruções de check-out?',
  fbCheckoutQ1: 'A que horas é o check-out?',
  fbCheckoutQ2: 'Quais são os passos do check-out?',
  fbCheckoutQ3: 'É possível um check-out tardio?',
  fbLocalTitle: 'Recomendações locais',
  fbLocalDesc: 'Locais aprovados, direções e links.',
  fbLocalP: 'Que locais recomenda?',
  hostTitle: 'Chat do anfitrião',
  hostSub: 'Escreva diretamente ao seu anfitrião{name}. As escaladas da IA também aparecem aqui quando o concierge precisa de uma resposta humana.',
  hostLoading: 'A carregar mensagens…',
  hostEmpty: 'Ainda não há mensagens. Envie uma nota e o seu anfitrião responderá aqui.',
  hostPlaceholder: 'Escreva uma mensagem…',
  hostError: 'Não foi possível enviar a sua mensagem.',
  hostEscTag: 'Escalada da IA',
  hostReplyingEsc: 'Está a responder a esta escalada — a sua resposta fica nesse tópico: “{text}”',
  hostReplyingTo: 'A responder a {who}: “{text}”',
  hostWhoHost: 'anfitrião',
  hostWhoMessage: 'mensagem',
  hostEscReplies: 'O seu anfitrião respondeu a esta escalada ({count})',
  hostNote: 'As respostas do anfitrião chegam aqui; se ativou, também enviamos um SMS neutro.',
  mTitle: 'Reportar manutenção',
  mSub: 'Descreva o problema. A IA sugere primeiro passos seguros e depois faz algumas perguntas rápidas para a equipa chegar preparada.',
  mPlaceholder: 'ex.: a torneira da cozinha está a pingar por baixo do armário…',
  mStart: 'Iniciar relatório',
  mStarting: 'A iniciar…',
  mResumeTitle: 'Tem um relatório em curso',
  mResumeCta: 'Continuar esse relatório',
  mAnswerPlaceholder: 'Escreva a sua resposta…',
  mTroubleshooting: 'Resolução de problemas',
  mSubmitted: 'Relatório enviado',
  mHostAlerted: 'O seu anfitrião foi alertado',
  mRefNumber: 'Número de referência',
  mDoneSub: 'O seu anfitrião e a equipa de manutenção foram notificados. Cite o número de referência no seguimento.',
  mSafetySub: 'Isto foi tratado como urgente e enviado de imediato ao seu anfitrião.',
  mReportAnother: 'Reportar outro problema',
  mError: 'Desculpe — algo correu mal. Tente novamente.',
  xTitle: 'Extras e comodidades',
  xEmpty: 'Não há extras nem comodidades disponíveis para esta estadia de momento.',
  xYourRequests: 'Os seus pedidos',
  xOptions: 'Opções',
  xQuantity: 'Quantidade',
  xYourName: 'O seu nome',
  xNamePlaceholder: 'De parte de quem deve o anfitrião esperar isto?',
  xWhen: 'Hora preferida (opcional)',
  xNote: 'Nota para o anfitrião (opcional)',
  xNotePlaceholder: 'Algo que devamos saber?',
  xRequest: 'Pedir',
  xSending: 'A enviar…',
  xSent: 'Pedido enviado',
  xSentSub: 'O seu anfitrião foi notificado e confirmará em breve.',
  xBrowseMore: 'Ver mais',
  xRef: 'Referência',
  xErrOption: 'Escolha uma opção antes de pedir.',
  xErrName: 'Adicione o seu nome para o anfitrião saber quem pede.',
  xNoRequests: 'Ainda não pediu nada.',
  xRefPrefix: 'Ref',
  xcatArrival: 'Chegada',
  xcatComfort: 'Conforto',
  xcatFood: 'Comida e bebida',
  xcatExperiences: 'Experiências',
  xcatTransport: 'Transporte',
  xcatMore: 'Mais',
  langTitle: 'Idioma',
  langSub: 'O concierge responde no seu idioma e o seu anfitrião recebe uma tradução das suas mensagens.',
  langSearch: 'Procurar idiomas…',
  langAuto: 'Automático',
  langAutoSub: 'Usar o idioma em que escrevo',
  langNoMatch: 'Nenhum idioma corresponde a “{query}”.',
  langChoose: 'Escolha o seu idioma',
  langCurrent: 'Idioma: {label}',
  lgTitle: 'Guia local',
  lgSub: 'Restaurantes, cafés, parques, golfe e mais perto de {property} — com as escolhas do seu anfitrião primeiro.',
  lgEmpty: 'Ainda não há locais registados para esta estadia.',
  lgEmptyHint: 'Pergunte ao concierge no chat do portal — pode recomendar locais da zona e pedir ao seu anfitrião os favoritos dele.',
  lgSearch: 'Procurar locais, notas, moradas…',
  lgAll: 'Tudo',
  lgHostPicks: 'Escolhas do anfitrião',
  lgMatching: 'Locais correspondentes',
  lgMore: 'Mais perto',
  lgAllPlaces: 'Todos os locais',
  lgNoMatch: 'Nenhum local corresponde à sua pesquisa.',
  lgDirections: 'Direções',
  lgWebsite: 'Website',
  lgCall: 'Ligar',
  lgHostPick: 'Escolha do anfitrião',
  lgHostNote: 'Nota do anfitrião:',
  lgBack: 'Portal',
};

const ptBR: Dict = {
  menu: 'Menu',
  back: 'Voltar',
  backToMenu: 'Voltar ao menu',
  continue: 'Continuar',
  checking: 'Verificando…',
  saving: 'Salvando…',
  loading: 'Carregando…',
  close: 'Fechar',
  reply: 'Responder',
  cancel: 'Cancelar',
  sendMessage: 'Enviar mensagem',
  themeToLight: 'Mudar para o modo claro',
  themeToDark: 'Mudar para o modo escuro',
  poweredBy: 'Com tecnologia Moche AI',
  codeKicker: 'Acesso de hóspedes',
  codeTitle: 'Boas-vindas a {property}',
  codeSub: 'Digite o código de estadia de 4 dígitos do seu anfitrião. Todos do seu grupo usam o mesmo código — em seguida você terá seu próprio concierge.',
  codeHint: 'Não tem o código? Pergunte ao seu anfitrião — está na mensagem da reserva.',
  codeError: 'Esse código não corresponde a esta estadia. Confirme com seu anfitrião e tente novamente.',
  regKicker: 'Um último passo',
  regTitle: 'Quem está chegando?',
  regSub: 'Cada pessoa do grupo tem seu próprio concierge. Conte quem você é — suas respostas, conversas e pedidos ficam com você.',
  regFirstName: 'Nome',
  regLastName: 'Sobrenome',
  regPhone: 'Número de celular (opcional)',
  regPhoneHint: 'Usado apenas para avisar por SMS quando o anfitrião responder.',
  regSms: 'Me envie um SMS neutro quando meu anfitrião responder.',
  regSmsNote: 'Podem ser aplicadas tarifas de mensagens e dados.',
  regTerms: 'Concordo com os termos do portal de hóspedes e a política de notificações do anfitrião.',
  regError: 'Não foi possível salvar seu perfil.',
  regSubmit: 'Abrir meu portal',
  menuWelcome: 'Boas-vindas',
  menuWelcomeName: 'Boas-vindas, {name}',
  menuSub: 'Como podemos ajudar em {property}?',
  menuHostPreview: 'Prévia do anfitrião — você está vendo o portal como um hóspede. Apenas «Fazer perguntas» está ativo na prévia.',
  cardAskTitle: 'Fazer perguntas',
  cardAskBlurb: 'Respostas instantâneas da IA sobre Wi-Fi, check-in, regras da casa, dicas locais e mais.',
  cardHostTitle: 'Falar diretamente com o anfitrião',
  cardHostBlurb: 'Fale com seu anfitrião ou a equipe da propriedade — uma pessoa real, não a IA.',
  cardMaintTitle: 'Reportar manutenção',
  cardMaintBlurb: 'Algo não está funcionando? Resolva com a IA e depois envie um relatório à equipe.',
  cardExtrasTitle: 'Extras e comodidades',
  cardExtrasBlurb: 'Explore e solicite extras, upgrades e experiências para sua estadia.',
  askTitle: 'Faça uma pergunta',
  askSub: 'Respostas confiáveis sobre a propriedade. Se o concierge não tiver certeza, ele avisa seu anfitrião em vez de chutar.',
  askEmpty: 'Escolha um cartão acima ou pergunte qualquer coisa sobre sua estadia.',
  askPlaceholder: 'Pergunte sobre Wi-Fi, check-in, lixo, lugares próximos…',
  askError: 'Algo deu errado. Tente novamente.',
  askEscNotice: 'Não tenho certeza da resposta, então avisei seu anfitrião. A resposta dele aparecerá no chat do anfitrião.',
  askOpenHostChat: 'Abrir chat do anfitrião',
  askSheetSub: 'Escolha uma pergunta — ou escreva a sua no chat.',
  askAppliances: 'Qual eletrodoméstico?',
  askApplianceSearch: 'Buscar eletrodomésticos…',
  askApplianceLoad: 'Carregando eletrodomésticos…',
  askApplianceNone: 'Nenhum eletrodoméstico corresponde a “{query}”.',
  askApplianceEmpty: 'Seu anfitrião ainda não cadastrou eletrodomésticos nesta propriedade. Avise-o para adicioná-los — ou pergunte no chat e o concierge encaminha se não souber.',
  askAppliancePing: 'Avisar o anfitrião',
  askAppliancePinged: 'Seu anfitrião foi avisado — a resposta dele aparecerá no chat.',
  askBackToAppliances: 'Voltar a todos os eletrodomésticos',
  askEmergency: 'Em caso de emergência, contate primeiro os serviços de emergência locais.',
  askTyping: 'O concierge está digitando…',
  hostReplyTag: 'Resposta do anfitrião',
  apUse: 'Como uso {name}?',
  apWhere: 'Onde fica {name}?',
  apOn: 'Como ligo {name}?',
  apClean: 'Como limpo ou reabasteço {name}?',
  apBroken: '{name} não está funcionando — o que faço?',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'Ajuda com rede e conexão.',
  fbWifiP: 'Qual é a rede Wi-Fi e a senha?',
  fbWifiQ1: 'Qual é o nome da rede Wi-Fi?',
  fbWifiQ2: 'Qual é a senha do Wi-Fi?',
  fbWifiQ3: 'Onde fica o roteador do Wi-Fi?',
  fbWifiQ4: 'O Wi-Fi não está funcionando — o que posso tentar?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Instruções de chegada e acesso.',
  fbCheckinP: 'Quais são as instruções de check-in?',
  fbCheckinQ1: 'A que horas é o check-in?',
  fbCheckinQ2: 'Como entro na propriedade?',
  fbCheckinQ3: 'É possível fazer check-in antecipado?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Passos e horários de saída.',
  fbCheckoutP: 'Quais são as instruções de check-out?',
  fbCheckoutQ1: 'A que horas é o check-out?',
  fbCheckoutQ2: 'Quais são os passos do check-out?',
  fbCheckoutQ3: 'É possível fazer check-out tardio?',
  fbLocalTitle: 'Recomendações locais',
  fbLocalDesc: 'Lugares aprovados, rotas e links.',
  fbLocalP: 'Quais lugares você recomenda?',
  hostTitle: 'Chat do anfitrião',
  hostSub: 'Escreva diretamente para seu anfitrião{name}. As escalações da IA também aparecem aqui quando o concierge precisa de uma resposta humana.',
  hostLoading: 'Carregando mensagens…',
  hostEmpty: 'Ainda não há mensagens. Envie uma mensagem e seu anfitrião responderá aqui.',
  hostPlaceholder: 'Escreva uma mensagem…',
  hostError: 'Não foi possível enviar sua mensagem.',
  hostEscTag: 'Escalação da IA',
  hostReplyingEsc: 'Você está respondendo a esta escalação — sua resposta fica nesse tópico: “{text}”',
  hostReplyingTo: 'Respondendo a {who}: “{text}”',
  hostWhoHost: 'anfitrião',
  hostWhoMessage: 'mensagem',
  hostEscReplies: 'Seu anfitrião respondeu a esta escalação ({count})',
  hostNote: 'As respostas do anfitrião chegam aqui; se você ativou, também enviamos um SMS neutro.',
  mTitle: 'Reportar manutenção',
  mSub: 'Descreva o problema. A IA primeiro sugere coisas seguras para tentar e depois faz algumas perguntas rápidas para a equipe chegar preparada.',
  mPlaceholder: 'ex.: a pia da cozinha está vazando embaixo do armário…',
  mStart: 'Iniciar relatório',
  mStarting: 'Iniciando…',
  mResumeTitle: 'Você tem um relatório em andamento',
  mResumeCta: 'Continuar esse relatório',
  mAnswerPlaceholder: 'Digite sua resposta…',
  mTroubleshooting: 'Resolução de problemas',
  mSubmitted: 'Relatório enviado',
  mHostAlerted: 'Seu anfitrião foi alertado',
  mRefNumber: 'Número de referência',
  mDoneSub: 'Seu anfitrião e a equipe de manutenção foram notificados. Cite o número de referência ao acompanhar.',
  mSafetySub: 'Isso foi tratado como urgente e enviado imediatamente ao seu anfitrião.',
  mReportAnother: 'Reportar outro problema',
  mError: 'Desculpe — algo deu errado. Tente novamente.',
  xTitle: 'Extras e comodidades',
  xEmpty: 'Não há extras ou comodidades disponíveis para esta estadia no momento.',
  xYourRequests: 'Seus pedidos',
  xOptions: 'Opções',
  xQuantity: 'Quantidade',
  xYourName: 'Seu nome',
  xNamePlaceholder: 'De parte de quem o anfitrião deve esperar isso?',
  xWhen: 'Horário preferido (opcional)',
  xNote: 'Nota para o anfitrião (opcional)',
  xNotePlaceholder: 'Algo que devemos saber?',
  xRequest: 'Solicitar',
  xSending: 'Enviando…',
  xSent: 'Pedido enviado',
  xSentSub: 'Seu anfitrião foi notificado e confirmará em breve.',
  xBrowseMore: 'Ver mais',
  xRef: 'Referência',
  xErrOption: 'Escolha uma opção antes de solicitar.',
  xErrName: 'Adicione seu nome para o anfitrião saber quem solicitou.',
  xNoRequests: 'Você ainda não solicitou nada.',
  xRefPrefix: 'Ref',
  xcatArrival: 'Chegada',
  xcatComfort: 'Conforto',
  xcatFood: 'Comida e bebida',
  xcatExperiences: 'Experiências',
  xcatTransport: 'Transporte',
  xcatMore: 'Mais',
  langTitle: 'Idioma',
  langSub: 'O concierge responde no seu idioma e seu anfitrião recebe uma tradução das suas mensagens.',
  langSearch: 'Buscar idiomas…',
  langAuto: 'Automático',
  langAutoSub: 'Usar o idioma em que eu escrevo',
  langNoMatch: 'Nenhum idioma corresponde a “{query}”.',
  langChoose: 'Escolha seu idioma',
  langCurrent: 'Idioma: {label}',
  lgTitle: 'Guia local',
  lgSub: 'Restaurantes, cafés, parques, golfe e mais perto de {property} — com as escolhas do seu anfitrião primeiro.',
  lgEmpty: 'Ainda não há lugares locais cadastrados para esta estadia.',
  lgEmptyHint: 'Pergunte ao concierge no chat do portal — ele pode recomendar lugares da região e pedir ao seu anfitrião os favoritos dele.',
  lgSearch: 'Buscar lugares, notas, endereços…',
  lgAll: 'Tudo',
  lgHostPicks: 'Escolhas do anfitrião',
  lgMatching: 'Lugares correspondentes',
  lgMore: 'Mais nas proximidades',
  lgAllPlaces: 'Todos os lugares',
  lgNoMatch: 'Nenhum lugar corresponde à sua busca.',
  lgDirections: 'Como chegar',
  lgWebsite: 'Site',
  lgCall: 'Ligar',
  lgHostPick: 'Escolha do anfitrião',
  lgHostNote: 'Nota do anfitrião:',
  lgBack: 'Portal',
};

const nl: Dict = {
  menu: 'Menu',
  back: 'Terug',
  backToMenu: 'Terug naar menu',
  continue: 'Doorgaan',
  checking: 'Controleren…',
  saving: 'Opslaan…',
  loading: 'Laden…',
  close: 'Sluiten',
  reply: 'Beantwoorden',
  cancel: 'Annuleren',
  sendMessage: 'Bericht versturen',
  themeToLight: 'Overschakelen naar lichte modus',
  themeToDark: 'Overschakelen naar donkere modus',
  poweredBy: 'Mogelijk gemaakt door Moche AI',
  codeKicker: 'Gastentoegang',
  codeTitle: 'Welkom bij {property}',
  codeSub: 'Voer de 4-cijferige verblijfscode van je host in. Iedereen in je gezelschap gebruikt dezelfde code — daarna krijg je je eigen concierge.',
  codeHint: 'Geen code? Vraag het je host — die staat in je boekingsbericht.',
  codeError: 'Deze code past niet bij dit verblijf. Vraag het je host en probeer opnieuw.',
  regKicker: 'Nog één stap',
  regTitle: 'Wie logt er in?',
  regSub: 'Iedereen in je gezelschap krijgt zijn eigen concierge. Vertel wie je bent — jouw antwoorden, chats en verzoeken blijven van jou.',
  regFirstName: 'Voornaam',
  regLastName: 'Achternaam',
  regPhone: 'Mobiel nummer (optioneel)',
  regPhoneHint: 'Wordt alleen gebruikt om je een sms te sturen als je host antwoordt.',
  regSms: 'Stuur mij een neutrale sms als mijn host antwoordt.',
  regSmsNote: 'Bericht- en datakosten kunnen van toepassing zijn.',
  regTerms: 'Ik ga akkoord met de voorwaarden van het gastenportaal en het meldingsbeleid van de host.',
  regError: 'Je profiel kon niet worden opgeslagen.',
  regSubmit: 'Open mijn portaal',
  menuWelcome: 'Welkom',
  menuWelcomeName: 'Welkom, {name}',
  menuSub: 'Hoe kunnen we je helpen bij {property}?',
  menuHostPreview: 'Host-voorbeeld — je ziet het portaal zoals een gast. Alleen «Vragen stellen» is actief in de voorbeeldweergave.',
  cardAskTitle: 'Vragen stellen',
  cardAskBlurb: 'Direct AI-antwoorden over wifi, check-in, huisregels, lokale tips en meer.',
  cardHostTitle: 'Direct bericht aan host',
  cardHostBlurb: 'Bereik je host of het personeel — een echt persoon, niet de AI.',
  cardMaintTitle: 'Onderhoud melden',
  cardMaintBlurb: 'Werkt er iets niet? Los het op met de AI en stuur daarna een melding naar het team.',
  cardExtrasTitle: 'Extra’s & voorzieningen',
  cardExtrasBlurb: 'Bekijk en vraag extra’s, upgrades en ervaringen voor je verblijf aan.',
  askTitle: 'Stel een vraag',
  askSub: 'Betrouwbare antwoorden over de accommodatie. Is de concierge niet zeker, dan waarschuwt hij je host in plaats van te gokken.',
  askEmpty: 'Kies hierboven een kaart of vraag alles over je verblijf.',
  askPlaceholder: 'Vraag naar wifi, check-in, afval, plekken in de buurt…',
  askError: 'Er ging iets mis. Probeer het opnieuw.',
  askEscNotice: 'Ik weet niet zeker of ik het juiste antwoord heb, dus ik heb je host gewaarschuwd. Zijn antwoord verschijnt in de host-chat.',
  askOpenHostChat: 'Open host-chat',
  askSheetSub: 'Kies een vraag — of typ je eigen vraag in de chat.',
  askAppliances: 'Welk apparaat?',
  askApplianceSearch: 'Apparaten zoeken…',
  askApplianceLoad: 'Apparaten laden…',
  askApplianceNone: 'Geen apparaten komen overeen met “{query}”.',
  askApplianceEmpty: 'Je host heeft nog geen apparaten voor deze accommodatie vermeld. Waarschuw hem zodat hij ze toevoegt — of vraag het in de chat en de concierge schakelt door als hij het niet weet.',
  askAppliancePing: 'Waarschuw de host',
  askAppliancePinged: 'Je host is gewaarschuwd — zijn antwoord verschijnt in de chat.',
  askBackToAppliances: 'Terug naar alle apparaten',
  askEmergency: 'Neem bij een noodgeval eerst contact op met de lokale hulpdiensten.',
  askTyping: 'De concierge is aan het typen…',
  hostReplyTag: 'Antwoord van host',
  apUse: 'Hoe gebruik ik {name}?',
  apWhere: 'Waar is {name}?',
  apOn: 'Hoe zet ik {name} aan?',
  apClean: 'Hoe maak ik {name} schoon of vul ik die bij?',
  apBroken: '{name} werkt niet — wat moet ik doen?',
  fbWifiTitle: 'Wifi',
  fbWifiDesc: 'Hulp bij netwerk en verbinding.',
  fbWifiP: 'Wat is de wifi-netwerknaam en het wachtwoord?',
  fbWifiQ1: 'Wat is de naam van het wifi-netwerk?',
  fbWifiQ2: 'Wat is het wifi-wachtwoord?',
  fbWifiQ3: 'Waar is de wifi-router?',
  fbWifiQ4: 'De wifi werkt niet — wat kan ik proberen?',
  fbCheckinTitle: 'Check-in',
  fbCheckinDesc: 'Instructies voor aankomst en toegang.',
  fbCheckinP: 'Wat zijn de check-in instructies?',
  fbCheckinQ1: 'Hoe laat is de check-in?',
  fbCheckinQ2: 'Hoe kom ik de accommodatie binnen?',
  fbCheckinQ3: 'Is vroeg inchecken mogelijk?',
  fbCheckoutTitle: 'Check-out',
  fbCheckoutDesc: 'Stappen en tijden voor vertrek.',
  fbCheckoutP: 'Wat zijn de check-out instructies?',
  fbCheckoutQ1: 'Hoe laat is de check-out?',
  fbCheckoutQ2: 'Wat zijn de check-out stappen?',
  fbCheckoutQ3: 'Is laat uitchecken mogelijk?',
  fbLocalTitle: 'Lokale aanbevelingen',
  fbLocalDesc: 'Goedgekeurde plekken, routes en links.',
  fbLocalP: 'Welke plekken in de buurt raad je aan?',
  hostTitle: 'Host-chat',
  hostSub: 'Stuur je host direct een bericht{name}. AI-escalaties verschijnen hier ook als de concierge een menselijk antwoord nodig heeft.',
  hostLoading: 'Berichten laden…',
  hostEmpty: 'Nog geen berichten. Stuur een bericht en je host antwoordt hier.',
  hostPlaceholder: 'Schrijf een bericht…',
  hostError: 'Je bericht kon niet worden verzonden.',
  hostEscTag: 'AI-escalatie',
  hostReplyingEsc: 'Je antwoordt op deze escalatie — je antwoord blijft in die thread: “{text}”',
  hostReplyingTo: 'Antwoord aan {who}: “{text}”',
  hostWhoHost: 'host',
  hostWhoMessage: 'bericht',
  hostEscReplies: 'Je host heeft op deze escalatie geantwoord ({count})',
  hostNote: 'Antwoorden van je host komen hier binnen; als je dat hebt aangezet, sturen we ook een neutrale sms.',
  mTitle: 'Onderhoud melden',
  mSub: 'Beschrijf het probleem. De AI stelt eerst veilige dingen voor om te proberen en stelt daarna een paar korte vragen zodat het team voorbereid komt.',
  mPlaceholder: 'bijv. De gootsteen lekt onder het keukenkastje…',
  mStart: 'Melding starten',
  mStarting: 'Starten…',
  mResumeTitle: 'Je hebt een lopende melding',
  mResumeCta: 'Ga verder met die melding',
  mAnswerPlaceholder: 'Typ je antwoord…',
  mTroubleshooting: 'Probleemoplossing',
  mSubmitted: 'Melding verzonden',
  mHostAlerted: 'Je host is gewaarschuwd',
  mRefNumber: 'Referentienummer',
  mDoneSub: 'Je host en het onderhoudsteam zijn op de hoogte gebracht. Noem het referentienummer bij vervolgvragen.',
  mSafetySub: 'Dit is als urgent behandeld en meteen naar je host gestuurd.',
  mReportAnother: 'Ander probleem melden',
  mError: 'Sorry — er ging iets mis. Probeer het opnieuw.',
  xTitle: 'Extra’s & voorzieningen',
  xEmpty: 'Er zijn nu geen extra’s of voorzieningen beschikbaar voor dit verblijf.',
  xYourRequests: 'Jouw verzoeken',
  xOptions: 'Opties',
  xQuantity: 'Aantal',
  xYourName: 'Je naam',
  xNamePlaceholder: 'Van wie mag de host dit verwachten?',
  xWhen: 'Gewenste tijd (optioneel)',
  xNote: 'Notitie voor de host (optioneel)',
  xNotePlaceholder: 'Iets dat we moeten weten?',
  xRequest: 'Aanvragen',
  xSending: 'Versturen…',
  xSent: 'Verzoek verzonden',
  xSentSub: 'Je host is op de hoogte gebracht en bevestigt binnenkort.',
  xBrowseMore: 'Meer bekijken',
  xRef: 'Referentie',
  xErrOption: 'Kies eerst een optie voordat je dit aanvraagt.',
  xErrName: 'Voeg je naam toe zodat de host weet van wie het verzoek komt.',
  xNoRequests: 'Je hebt nog niets aangevraagd.',
  xRefPrefix: 'Ref',
  xcatArrival: 'Aankomst',
  xcatComfort: 'Comfort',
  xcatFood: 'Eten & drinken',
  xcatExperiences: 'Ervaringen',
  xcatTransport: 'Vervoer',
  xcatMore: 'Meer',
  langTitle: 'Taal',
  langSub: 'De concierge antwoordt in jouw taal en je host ontvangt een vertaling van je berichten.',
  langSearch: 'Talen zoeken…',
  langAuto: 'Automatisch',
  langAutoSub: 'De taal gebruiken waarin ik schrijf',
  langNoMatch: 'Geen talen komen overeen met “{query}”.',
  langChoose: 'Kies je taal',
  langCurrent: 'Taal: {label}',
  lgTitle: 'Lokale gids',
  lgSub: 'Restaurants, cafés, parken, golf en meer in de buurt van {property} — met de favorieten van je host eerst.',
  lgEmpty: 'Er zijn nog geen lokale plekken voor dit verblijf vermeld.',
  lgEmptyHint: 'Vraag het de concierge in de portal-chat — hij kan plekken in de buurt aanraden en je host om zijn favorieten vragen.',
  lgSearch: 'Zoek plekken, notities, adressen…',
  lgAll: 'Alles',
  lgHostPicks: 'Favorieten van de host',
  lgMatching: 'Passende plekken',
  lgMore: 'Meer in de buurt',
  lgAllPlaces: 'Alle plekken',
  lgNoMatch: 'Geen plekken komen overeen met je zoekopdracht.',
  lgDirections: 'Route',
  lgWebsite: 'Website',
  lgCall: 'Bellen',
  lgHostPick: 'Favoriet van de host',
  lgHostNote: 'Notitie van de host:',
  lgBack: 'Portaal',
};

const zhHans: Dict = {
  menu: '菜单',
  back: '返回',
  backToMenu: '返回菜单',
  continue: '继续',
  checking: '正在验证…',
  saving: '正在保存…',
  loading: '加载中…',
  close: '关闭',
  reply: '回复',
  cancel: '取消',
  sendMessage: '发送消息',
  themeToLight: '切换为浅色模式',
  themeToDark: '切换为深色模式',
  poweredBy: '由 Moche AI 提供支持',
  codeKicker: '宾客入口',
  codeTitle: '欢迎来到{property}',
  codeSub: '请输入房东分享的4位数入住码。同行的所有人都使用同一个代码——接下来您将获得自己的专属礼宾助手。',
  codeHint: '没有代码？请联系房东——它在您的预订信息中。',
  codeError: '该代码与本次入住不符。请与房东确认后重试。',
  regKicker: '最后一步',
  regTitle: '请问您是哪位？',
  regSub: '同行每位成员都有自己的专属礼宾助手。请告诉我们您是谁——您的回答、聊天和请求都只属于您。',
  regFirstName: '名字',
  regLastName: '姓氏',
  regPhone: '手机号码（可选）',
  regPhoneHint: '仅用于在房东回复时向您发送短信提醒。',
  regSms: '当房东回复时，给我发送一条中性短信提醒。',
  regSmsNote: '可能会产生短信和流量费用。',
  regTerms: '我同意宾客门户条款和房东通知政策。',
  regError: '无法保存您的资料。',
  regSubmit: '打开我的门户',
  menuWelcome: '欢迎',
  menuWelcomeName: '欢迎，{name}',
  menuSub: '在{property}有什么可以帮您？',
  menuHostPreview: '房东预览——您正以宾客身份查看门户。预览中仅“提问”可用。',
  cardAskTitle: '提问',
  cardAskBlurb: '关于 Wi-Fi、入住、房屋守则、本地推荐等问题的即时 AI 回答。',
  cardHostTitle: '直接联系房东',
  cardHostBlurb: '联系您的房东或物业工作人员——真人回复，不是 AI。',
  cardMaintTitle: '报修维护',
  cardMaintBlurb: '有东西坏了？先让 AI 帮您排查，再向团队提交报修单。',
  cardExtrasTitle: '附加服务与设施',
  cardExtrasBlurb: '浏览并申请您入住期间的加购、升级和体验项目。',
  askTitle: '提问',
  askSub: '获取可靠的房源相关回答。如果礼宾助手不确定，它会通知房东而不是猜测。',
  askEmpty: '选择上方卡片，或询问任何关于入住的问题。',
  askPlaceholder: '询问 Wi-Fi、入住、垃圾、附近地点…',
  askError: '出错了，请重试。',
  askEscNotice: '我不确定答案是否正确，因此已通知您的房东。房东的回复将显示在“房东聊天”中。',
  askOpenHostChat: '打开房东聊天',
  askSheetSub: '选择一个问题——或在下方聊天中输入您自己的问题。',
  askAppliances: '哪个电器？',
  askApplianceSearch: '搜索电器…',
  askApplianceLoad: '正在加载电器…',
  askApplianceNone: '没有与“{query}”匹配的电器。',
  askApplianceEmpty: '房东尚未为此房源登记电器。通知房东添加——或直接在聊天中提问，礼宾助手不知道时会代为转达。',
  askAppliancePing: '通知房东',
  askAppliancePinged: '已通知房东——他的回复将显示在聊天中。',
  askBackToAppliances: '返回所有电器',
  askEmergency: '如遇紧急情况，请先联系当地紧急服务。',
  askTyping: '礼宾助手正在输入…',
  hostReplyTag: '房东回复',
  apUse: '如何使用{name}？',
  apWhere: '{name}在哪里？',
  apOn: '如何打开{name}？',
  apClean: '如何清洁或补充{name}？',
  apBroken: '{name}坏了——我该怎么办？',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: '网络与连接帮助。',
  fbWifiP: 'Wi-Fi 网络和密码是什么？',
  fbWifiQ1: 'Wi-Fi 网络名称是什么？',
  fbWifiQ2: 'Wi-Fi 密码是什么？',
  fbWifiQ3: 'Wi-Fi 路由器在哪里？',
  fbWifiQ4: 'Wi-Fi 用不了——我可以尝试什么？',
  fbCheckinTitle: '入住',
  fbCheckinDesc: '到达与进入指引。',
  fbCheckinP: '入住说明是什么？',
  fbCheckinQ1: '几点可以入住？',
  fbCheckinQ2: '如何进入房源？',
  fbCheckinQ3: '可以提前入住吗？',
  fbCheckoutTitle: '退房',
  fbCheckoutDesc: '退房步骤与时间。',
  fbCheckoutP: '退房说明是什么？',
  fbCheckoutQ1: '几点退房？',
  fbCheckoutQ2: '退房步骤是什么？',
  fbCheckoutQ3: '可以延迟退房吗？',
  fbLocalTitle: '本地推荐',
  fbLocalDesc: '经房东认可的地点、路线和链接。',
  fbLocalP: '您推荐哪些本地去处？',
  hostTitle: '房东聊天',
  hostSub: '直接给房东发消息{name}。当礼宾助手需要人工回答时，AI 升级也会显示在这里。',
  hostLoading: '正在加载消息…',
  hostEmpty: '还没有消息。发一条消息，房东会在这里回复。',
  hostPlaceholder: '写一条消息…',
  hostError: '消息发送失败。',
  hostEscTag: 'AI 升级',
  hostReplyingEsc: '您正在回复此升级——您的回复将保留在该话题中：“{text}”',
  hostReplyingTo: '回复{who}：“{text}”',
  hostWhoHost: '房东',
  hostWhoMessage: '消息',
  hostEscReplies: '房东已回复此升级（{count}）',
  hostNote: '房东的回复会出现在这里；如您已开启，我们还会发送一条中性短信提醒。',
  mTitle: '报修维护',
  mSub: '请描述问题。AI 会先建议安全的尝试方法，然后问几个简单的问题，让维修团队有备而来。',
  mPlaceholder: '例如：厨房水槽下方的柜子在漏水…',
  mStart: '开始报修',
  mStarting: '正在提交…',
  mResumeTitle: '您有一个进行中的报修',
  mResumeCta: '继续该报修',
  mAnswerPlaceholder: '输入您的回答…',
  mTroubleshooting: '故障排查',
  mSubmitted: '报修已提交',
  mHostAlerted: '已通知您的房东',
  mRefNumber: '参考编号',
  mDoneSub: '您的房东和维修团队已收到通知。跟进时请提供参考编号。',
  mSafetySub: '此问题已作为紧急事项立即发送给您的房东。',
  mReportAnother: '报告其他问题',
  mError: '抱歉——出错了，请重试。',
  xTitle: '附加服务与设施',
  xEmpty: '本次入住暂无可用的附加服务或设施。',
  xYourRequests: '您的请求',
  xOptions: '选项',
  xQuantity: '数量',
  xYourName: '您的姓名',
  xNamePlaceholder: '房东应该知道这是谁的需求？',
  xWhen: '期望时间（可选）',
  xNote: '给房东的备注（可选）',
  xNotePlaceholder: '有什么需要我们了解的吗？',
  xRequest: '申请',
  xSending: '正在发送…',
  xSent: '请求已发送',
  xSentSub: '房东已收到通知，将尽快确认。',
  xBrowseMore: '继续浏览',
  xRef: '参考编号',
  xErrOption: '请先选择一个选项再申请。',
  xErrName: '请填写您的姓名，以便房东知道是谁的请求。',
  xNoRequests: '您还没有提出任何请求。',
  xRefPrefix: '编号',
  xcatArrival: '到达',
  xcatComfort: '舒适',
  xcatFood: '餐饮',
  xcatExperiences: '体验',
  xcatTransport: '交通',
  xcatMore: '更多',
  langTitle: '语言',
  langSub: '礼宾助手会用您的语言回复，房东会收到您消息的翻译。',
  langSearch: '搜索语言…',
  langAuto: '自动',
  langAutoSub: '使用我书写时所用的语言',
  langNoMatch: '没有与“{query}”匹配的语言。',
  langChoose: '选择您的语言',
  langCurrent: '语言：{label}',
  lgTitle: '本地指南',
  lgSub: '{property}附近的餐厅、咖啡馆、公园、高尔夫等——房东推荐优先。',
  lgEmpty: '本次入住暂未登记本地地点。',
  lgEmptyHint: '在门户聊天中询问礼宾助手——它可以推荐周边地点并向房东询问他的推荐。',
  lgSearch: '搜索地点、备注、地址…',
  lgAll: '全部',
  lgHostPicks: '房东推荐',
  lgMatching: '匹配的地点',
  lgMore: '更多附近地点',
  lgAllPlaces: '所有地点',
  lgNoMatch: '没有符合您搜索的地点。',
  lgDirections: '导航',
  lgWebsite: '网站',
  lgCall: '电话',
  lgHostPick: '房东推荐',
  lgHostNote: '房东备注：',
  lgBack: '门户',
};

const ja: Dict = {
  menu: 'メニュー',
  back: '戻る',
  backToMenu: 'メニューに戻る',
  continue: '続ける',
  checking: '確認中…',
  saving: '保存中…',
  loading: '読み込み中…',
  close: '閉じる',
  reply: '返信',
  cancel: 'キャンセル',
  sendMessage: 'メッセージを送信',
  themeToLight: 'ライトモードに切り替え',
  themeToDark: 'ダークモードに切り替え',
  poweredBy: 'Powered by Moche AI',
  codeKicker: 'ゲストアクセス',
  codeTitle: '{property}へようこそ',
  codeSub: 'ホストが共有した4桁の宿泊コードを入力してください。グループ全員が同じコードを使います——この後、あなた専用のコンシェルジュが使えるようになります。',
  codeHint: 'コードがわからない場合はホストにお尋ねください——予約メッセージに記載されています。',
  codeError: 'このコードはこの宿泊と一致しません。ホストに確認してもう一度お試しください。',
  regKicker: 'あと一歩',
  regTitle: 'ご利用になる方は？',
  regSub: 'グループの全員がそれぞれのコンシェルジュを持てます。お名前を教えてください——回答・チャット・リクエストはあなた専用です。',
  regFirstName: '名',
  regLastName: '姓',
  regPhone: '携帯電話番号（任意）',
  regPhoneHint: 'ホストが返信したときにSMSでお知らせするためだけに使います。',
  regSms: 'ホストが返信したら中立的なSMSで通知する',
  regSmsNote: 'メッセージ・データ通信料がかかる場合があります。',
  regTerms: 'ゲストポータルの利用規約とホスト通知ポリシーに同意します。',
  regError: 'プロフィールを保存できませんでした。',
  regSubmit: 'ポータルを開く',
  menuWelcome: 'ようこそ',
  menuWelcomeName: 'ようこそ、{name}さん',
  menuSub: '{property}で何かお手伝いしましょうか？',
  menuHostPreview: 'ホストプレビュー——ゲストに見えるポータルを表示しています。プレビューでは「質問する」のみ有効です。',
  cardAskTitle: '質問する',
  cardAskBlurb: 'Wi-Fi、チェックイン、ハウスルール、周辺情報などにAIが即回答。',
  cardHostTitle: 'ホストに直接連絡',
  cardHostBlurb: 'ホストやスタッフに連絡できます——AIではなく実際の人が対応します。',
  cardMaintTitle: '修繕を報告',
  cardMaintBlurb: '不具合がありますか？AIと一緒に確認し、チームに報告を送ります。',
  cardExtrasTitle: 'オプション＆設備',
  cardExtrasBlurb: '滞在を充実させる追加オプション、アップグレード、体験を探してリクエスト。',
  askTitle: '質問する',
  askSub: '物件に関する信頼できる回答を得られます。コンシェルジュが確信を持てない場合は、推測せずホストに確認します。',
  askEmpty: '上のカードを選ぶか、滞在について何でも聞いてください。',
  askPlaceholder: 'Wi-Fi、チェックイン、ゴミ、周辺スポットなど…',
  askError: '問題が発生しました。もう一度お試しください。',
  askEscNotice: '正確な回答ができないため、ホストに通知しました。返信は「ホストチャット」に表示されます。',
  askOpenHostChat: 'ホストチャットを開く',
  askSheetSub: '質問を選ぶか、下のチャットに直接入力してください。',
  askAppliances: 'どの設備・家電ですか？',
  askApplianceSearch: '設備・家電を検索…',
  askApplianceLoad: '読み込み中…',
  askApplianceNone: '「{query}」に一致するものはありません。',
  askApplianceEmpty: 'この物件にはまだ設備・家電が登録されていません。ホストに通知して追加してもらうか、チャットで質問すればコンシェルジュがわからない場合に転送します。',
  askAppliancePing: 'ホストに通知',
  askAppliancePinged: 'ホストに通知しました——返信はチャットに表示されます。',
  askBackToAppliances: 'すべての設備・家電に戻る',
  askEmergency: '緊急の場合は、まず現地の緊急サービスに連絡してください。',
  askTyping: 'コンシェルジュが入力中…',
  hostReplyTag: 'ホストからの返信',
  apUse: '{name}の使い方は？',
  apWhere: '{name}はどこにありますか？',
  apOn: '{name}の電源の入れ方は？',
  apClean: '{name}の掃除・補充方法は？',
  apBroken: '{name}が動きません——どうすればいいですか？',
  fbWifiTitle: 'Wi-Fi',
  fbWifiDesc: 'ネットワークと接続のヘルプ。',
  fbWifiP: 'Wi-Fiのネットワーク名とパスワードは？',
  fbWifiQ1: 'Wi-Fiのネットワーク名は？',
  fbWifiQ2: 'Wi-Fiのパスワードは？',
  fbWifiQ3: 'Wi-Fiルーターはどこですか？',
  fbWifiQ4: 'Wi-Fiがつながりません——何を試せばいいですか？',
  fbCheckinTitle: 'チェックイン',
  fbCheckinDesc: '到着と入り方の案内。',
  fbCheckinP: 'チェックインの手順は？',
  fbCheckinQ1: 'チェックインは何時ですか？',
  fbCheckinQ2: '物件への入り方は？',
  fbCheckinQ3: 'アーリーチェックインは可能ですか？',
  fbCheckoutTitle: 'チェックアウト',
  fbCheckoutDesc: '出発の手順と時間。',
  fbCheckoutP: 'チェックアウトの手順は？',
  fbCheckoutQ1: 'チェックアウトは何時ですか？',
  fbCheckoutQ2: 'チェックアウトの手順は？',
  fbCheckoutQ3: 'レイトチェックアウトは可能ですか？',
  fbLocalTitle: '周辺のおすすめ',
  fbLocalDesc: '承認されたスポット、行き方、リンク。',
  fbLocalP: 'おすすめの周辺スポットは？',
  hostTitle: 'ホストチャット',
  hostSub: 'ホストに直接メッセージを送れます{name}。コンシェルジュが人の回答を必要とする場合、AIエスカレーションもここに表示されます。',
  hostLoading: 'メッセージを読み込み中…',
  hostEmpty: 'まだメッセージはありません。メッセージを送ると、ここにホストが返信します。',
  hostPlaceholder: 'メッセージを書く…',
  hostError: 'メッセージを送信できませんでした。',
  hostEscTag: 'AIエスカレーション',
  hostReplyingEsc: 'このエスカレーションに返信中——返信はこのスレッドに残ります：「{text}」',
  hostReplyingTo: '{who}に返信：「{text}」',
  hostWhoHost: 'ホスト',
  hostWhoMessage: 'メッセージ',
  hostEscReplies: 'ホストがこのエスカレーションに返信しました（{count}）',
  hostNote: 'ホストの返信はここに届きます。オンにしている場合は、中立的なSMSもお送りします。',
  mTitle: '修繕を報告',
  mSub: '問題を説明してください。AIがまず安全な対処法を提案し、その後いくつか質問して、チームが準備して到着できるようにします。',
  mPlaceholder: '例：キッチンのシンクの下のキャビネットから水漏れしています…',
  mStart: '報告を開始',
  mStarting: '開始中…',
  mResumeTitle: '進行中の報告があります',
  mResumeCta: 'その報告を続ける',
  mAnswerPlaceholder: '回答を入力…',
  mTroubleshooting: 'トラブルシューティング',
  mSubmitted: '報告を送信しました',
  mHostAlerted: 'ホストに通知しました',
  mRefNumber: '参照番号',
  mDoneSub: 'ホストとメンテナンスチームに通知しました。お問い合わせの際は参照番号をお知らせください。',
  mSafetySub: '緊急として扱い、すぐにホストへ送信しました。',
  mReportAnother: '別の問題を報告',
  mError: '申し訳ありません——問題が発生しました。もう一度お試しください。',
  xTitle: 'オプション＆設備',
  xEmpty: '現在この滞在で利用できるオプションや設備はありません。',
  xYourRequests: 'あなたのリクエスト',
  xOptions: 'オプション',
  xQuantity: '数量',
  xYourName: 'お名前',
  xNamePlaceholder: '誰からのリクエストかホストに伝わるようにしましょう',
  xWhen: '希望日時（任意）',
  xNote: 'ホストへのメモ（任意）',
  xNotePlaceholder: '知っておいてほしいことはありますか？',
  xRequest: 'リクエスト',
  xSending: '送信中…',
  xSent: 'リクエストを送信しました',
  xSentSub: 'ホストに通知しました。まもなく確認があります。',
  xBrowseMore: 'もっと見る',
  xRef: '参照番号',
  xErrOption: 'リクエスト前にオプションを選択してください。',
  xErrName: '誰からのリクエストかわかるよう、お名前を入力してください。',
  xNoRequests: 'まだリクエストはありません。',
  xRefPrefix: '参照',
  xcatArrival: '到着',
  xcatComfort: '快適さ',
  xcatFood: '飲食',
  xcatExperiences: '体験',
  xcatTransport: '交通',
  xcatMore: 'その他',
  langTitle: '言語',
  langSub: 'コンシェルジュはあなたの言語で返信し、ホストにはあなたのメッセージの翻訳が届きます。',
  langSearch: '言語を検索…',
  langAuto: '自動',
  langAutoSub: '書いている言語に合わせる',
  langNoMatch: '「{query}」に一致する言語はありません。',
  langChoose: '言語を選択',
  langCurrent: '言語：{label}',
  lgTitle: 'ローカルガイド',
  lgSub: '{property}の近くのレストラン、カフェ、公園、ゴルフなど——ホストのおすすめを最初に。',
  lgEmpty: 'この滞在にはまだ周辺スポットが登録されていません。',
  lgEmptyHint: 'ポータルのチャットでコンシェルジュに聞いてみてください——周辺スポットを提案したり、ホストにおすすめを尋ねたりできます。',
  lgSearch: 'スポット、メモ、住所を検索…',
  lgAll: 'すべて',
  lgHostPicks: 'ホストのおすすめ',
  lgMatching: '一致するスポット',
  lgMore: '近くのその他',
  lgAllPlaces: 'すべてのスポット',
  lgNoMatch: '検索に一致するスポットはありません。',
  lgDirections: '道順',
  lgWebsite: 'ウェブサイト',
  lgCall: '電話',
  lgHostPick: 'ホストのおすすめ',
  lgHostNote: 'ホストのメモ：',
  lgBack: 'ポータル',
};

// Lookup keys are lower-cased BCP-47 codes, matching resolveLanguage() output.
const DICTS: Record<string, Dict> = {
  en,
  es,
  fr,
  de,
  it,
  pt,
  'pt-br': ptBR,
  nl,
  'zh-hans': zhHans,
  ja,
};

/** Languages with a shipped UI dictionary (everything else falls back to English). */
export const PORTAL_STRING_LOCALES = Object.keys(DICTS);

/**
 * Returns the portal translator for a guest language choice (or null/auto).
 * Missing keys and unlisted languages fall back to English; {var} placeholders
 * are interpolated. Pure — safe to call per render.
 */
export function portalT(language: string | null | undefined): PortalT {
  const code = resolveLanguage(language)?.code.toLowerCase();
  const dict = (code && DICTS[code]) || en;
  return (key, vars) => {
    let text = dict[key] ?? en[key] ?? key;
    if (vars) {
      for (const [name, value] of Object.entries(vars)) {
        text = text.split(`{${name}}`).join(String(value));
      }
    }
    return text;
  };
}
