-- Migration: add human-quotable stay_reference to public.stays
-- Date: 2026-08-26
-- Plan: planning/reports-rework-execution-plan-2026-08-26.md (section 3)
-- Reversible: ALTER TABLE public.stays DROP COLUMN stay_reference;

BEGIN;

ALTER TABLE public.stays
  ADD COLUMN IF NOT EXISTS stay_reference text;

UPDATE public.stays
SET stay_reference = 'STY-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
WHERE stay_reference IS NULL;

ALTER TABLE public.stays
  ALTER COLUMN stay_reference SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS stays_stay_reference_key
  ON public.stays (stay_reference);

COMMENT ON COLUMN public.stays.stay_reference IS
  'Human-quotable stay reference (STY-XXXXXX). Generated by application code at stay creation; unique globally. Displayable/filterable counterpart to the HMAC-hashed 4-digit visit code, which is never stored in plaintext.';

COMMIT;
