INSERT INTO public.field_registry (field_id,label,domain,system_section,type,enum_values,sensitivity_tier,default_audience,phase,ttl_days,storage_table,storage_column,storage_vault,gap_weight,hard_block,applicability,requires_on_failure,on_failure_field,scrape_hint,interview_prompt,registry_version) VALUES
('access_backup_method','Backup access method','access_security',false,'text',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay"}'::text[],365,'brain_values','value',false,2.0,false,'always',false,NULL,NULL,'If the keypad is dead or the code fails, how else does a guest get in tonight?',1),
('access_code_lifecycle','Access code lifecycle','access_security',false,'text',NULL,'host_only'::public.sensitivity_tier,'host_private'::public.audience_tier,'{"pre-arrival"}'::text[],90,'brain_values','value',false,1.0,false,'has_smart_lock',false,NULL,NULL,'Does the code change between stays? Who rotates it, and when?',1),
('after_hours_escalation','After-hours escalation','maintenance_escalation',false,'text',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],180,'brain_values','value',false,1.5,false,'always',false,NULL,NULL,'Who handles a 2am problem if the primary contact does not answer?',1),
('age_child_policy','Age & child policy','policies_money',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,0.5,false,'always',false,NULL,'House rules; ''Suitable for children'' / ''infants'' rows.','Any age restrictions? Is the space suitable for infants or children?',1),
('appliance_list','Appliance list','amenities',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,'Amenities section; kitchen and laundry groups.','Which major appliances are available to guests?',1),
('area_safety_notes','Area safety notes','local_area',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"pre-arrival","mid-stay"}'::text[],180,'brain_values','value',false,0.5,false,'always',false,NULL,NULL,'Anything guests should know about the area after dark?',1),
('audit_verified_at','Verified at','sys_provenance_audit',true,'date',NULL,'host_only'::public.sensitivity_tier,'system_internal'::public.audience_tier,'{"booking"}'::text[],NULL,'brain_values','verified_at',false,0.0,false,'always',false,NULL,NULL,'System field. Not host-facing.',1),
('automation_gate_decision','Auto-publish gate decision','sys_automations_rules',true,'enum','["would_have_published", "held_for_host"]'::jsonb,'host_only'::public.sensitivity_tier,'system_internal'::public.audience_tier,'{"booking"}'::text[],NULL,'brain_values','value',false,0.0,false,'always',false,NULL,NULL,'System field. Not host-facing.',1),
('bed_configuration','Bed count, sizes & configuration','space_details',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","pre-arrival"}'::text[],365,'brain_values','value',false,1.5,false,'always',false,NULL,'''Where you''''ll sleep'' section; per-room bed cards.','How many beds, what sizes, and in which rooms?',1),
('checkin_flexibility','Early check-in policy & fee','access_security',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"booking","pre-arrival"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'Can guests check in early, and is there a fee?',1),
('checkin_time','Check-in time','access_security',false,'time',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","pre-arrival"}'::text[],365,'brain_values','value',false,2.0,false,'always',false,NULL,'House rules / ''Check-in'' row on the listing page.','What time can guests check in?',1),
('checkout_checklist','Checkout checklist','checkout',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"checkout"}'::text[],365,'brain_values','value',false,1.5,false,'always',false,NULL,NULL,'What must a guest do before leaving — dishes, linens, thermostat, lights?',1),
('checkout_time','Checkout time','access_security',false,'time',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","mid-stay","checkout"}'::text[],365,'brain_values','value',false,3.0,true,'always',false,NULL,'House rules / ''Checkout'' row on the listing page.','What time must guests check out?',1),
('climate_control','Heating & cooling','amenities',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,'Amenities section plus review text mentioning hot/cold rooms.','How do guests control heat and AC, and are there any known weak spots (e.g. ''AC struggles upstairs'')?',1),
('deposit_damage_policy','Deposit & damage policy','policies_money',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"booking","checkout"}'::text[],365,'brain_values','value',false,1.0,false,'charges_deposit',false,NULL,NULL,'Is there a security deposit or damage policy guests should know about?',1)
ON CONFLICT (field_id) DO UPDATE SET label=EXCLUDED.label,domain=EXCLUDED.domain,system_section=EXCLUDED.system_section,type=EXCLUDED.type,enum_values=EXCLUDED.enum_values,sensitivity_tier=EXCLUDED.sensitivity_tier,default_audience=EXCLUDED.default_audience,phase=EXCLUDED.phase,ttl_days=EXCLUDED.ttl_days,storage_table=EXCLUDED.storage_table,storage_column=EXCLUDED.storage_column,storage_vault=EXCLUDED.storage_vault,gap_weight=EXCLUDED.gap_weight,hard_block=EXCLUDED.hard_block,applicability=EXCLUDED.applicability,requires_on_failure=EXCLUDED.requires_on_failure,on_failure_field=EXCLUDED.on_failure_field,scrape_hint=EXCLUDED.scrape_hint,interview_prompt=EXCLUDED.interview_prompt,registry_version=EXCLUDED.registry_version;
