INSERT INTO public.field_registry (field_id,label,domain,system_section,type,enum_values,sensitivity_tier,default_audience,phase,ttl_days,storage_table,storage_column,storage_vault,gap_weight,hard_block,applicability,requires_on_failure,on_failure_field,scrape_hint,interview_prompt,registry_version) VALUES
('pet_fee','Pet fee','policies_money',false,'number',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,0.5,false,'allows_pets',false,NULL,NULL,'What is the pet fee, and is it per stay or per night?',1),
('pet_policy','Pet policy & fees','policies_money',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,'House rules section; ''Pets allowed'' row.','Are pets allowed? Any fee, size, or breed limits?',1),
('plumbing_troubleshooting','Plumbing troubleshooting','maintenance_escalation',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',true,'maintenance_emergency_contact',NULL,'What should a guest try for a clogged toilet or slow drain before calling you?',1),
('pool_instructions','Pool instructions & hours','amenities',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'has_pool',true,'maintenance_emergency_contact',NULL,'What are the pool hours, rules, and any heating or safety notes?',1),
('provenance_source_rank','Provenance source rank','sys_provenance_audit',true,'enum','["host_verified", "pms_sync", "host_chat", "escalation", "firecrawl", "inferred"]'::jsonb,'host_only'::public.sensitivity_tier,'system_internal'::public.audience_tier,'{"booking"}'::text[],NULL,'brain_values','source',false,0.0,false,'always',false,NULL,NULL,'System field. Not host-facing.',1),
('quiet_hours','Quiet hours','house_rules',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,'House rules section; ''Quiet hours'' row.','What are the quiet hours, and is there an HOA or city noise rule?',1),
('restaurant_recommendations','Restaurant recommendations','local_area',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"pre-arrival","mid-stay"}'::text[],180,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'Name two or three nearby places you would actually send a guest to.',1),
('safety_escalation_record','Safety escalation record','sys_safety_escalations',true,'text',NULL,'host_only'::public.sensitivity_tier,'system_internal'::public.audience_tier,'{"mid-stay"}'::text[],NULL,'brain_values','value',false,0.0,false,'always',false,NULL,NULL,'System field. Not host-facing.',1),
('scrape_log_entry','Scrape log entry','sys_sources_scrape_log',true,'text',NULL,'host_only'::public.sensitivity_tier,'system_internal'::public.audience_tier,'{"booking"}'::text[],NULL,'brain_values','value',false,0.0,false,'always',false,NULL,NULL,'System field. Not host-facing.',1),
('security_camera_disclosure','Security camera disclosure','access_security',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","pre-arrival"}'::text[],365,'brain_values','value',false,1.5,false,'has_security_cameras',false,NULL,'Safety & property section; ''Security cameras on property'' row.','Are there any exterior cameras or recording devices? Disclosure is legally required.',1),
('smoking_policy','Smoking policy','house_rules',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,0.5,false,'always',false,NULL,'House rules section; ''No smoking'' row.','Is smoking or vaping permitted anywhere on the property?',1),
('transit_options','Transit options','local_area',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","pre-arrival","mid-stay"}'::text[],180,'brain_values','value',false,1.0,false,'always',false,NULL,'''Getting around'' / neighborhood section.','What transit, rideshare, or airport options do guests use?',1),
('trash_schedule','Trash & recycling','house_rules',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay","checkout"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'Where does trash go, and is there a collection day guests must handle?',1),
('unexpected_charge_disclosure','Additional charges','policies_money',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,1.5,false,'always',false,NULL,NULL,'Are there any charges a guest could be surprised by — resort fee, cleaning, utilities, extra guest?',1),
('utility_shutoff_locations','Utility shutoff locations','maintenance_escalation',false,'text',NULL,'host_only'::public.sensitivity_tier,'staff_ops'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'Where are the water shutoff, breaker panel, and gas valve?',1)
ON CONFLICT (field_id) DO UPDATE SET label=EXCLUDED.label,domain=EXCLUDED.domain,system_section=EXCLUDED.system_section,type=EXCLUDED.type,enum_values=EXCLUDED.enum_values,sensitivity_tier=EXCLUDED.sensitivity_tier,default_audience=EXCLUDED.default_audience,phase=EXCLUDED.phase,ttl_days=EXCLUDED.ttl_days,storage_table=EXCLUDED.storage_table,storage_column=EXCLUDED.storage_column,storage_vault=EXCLUDED.storage_vault,gap_weight=EXCLUDED.gap_weight,hard_block=EXCLUDED.hard_block,applicability=EXCLUDED.applicability,requires_on_failure=EXCLUDED.requires_on_failure,on_failure_field=EXCLUDED.on_failure_field,scrape_hint=EXCLUDED.scrape_hint,interview_prompt=EXCLUDED.interview_prompt,registry_version=EXCLUDED.registry_version;
