INSERT INTO public.field_registry (field_id,label,domain,system_section,type,enum_values,sensitivity_tier,default_audience,phase,ttl_days,storage_table,storage_column,storage_vault,gap_weight,hard_block,applicability,requires_on_failure,on_failure_field,scrape_hint,interview_prompt,registry_version) VALUES
('wifi_speed_tier','Internet speed','connectivity',false,'string',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","pre-arrival"}'::text[],365,'brain_values','value',false,0.5,false,'always',false,NULL,'Amenities section; ''Fast wifi'' badge often states Mbps.','Roughly what download speed can guests expect?',1),
('wifi_troubleshooting','Wi-Fi troubleshooting / fallback','connectivity',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.5,false,'always',false,NULL,NULL,'If the Wi-Fi is down at 11pm, what should a guest do? Where is the router, and who do they call?',1),
('appliance_troubleshooting','Appliance troubleshooting','maintenance_escalation',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',true,'maintenance_emergency_contact',NULL,'Any appliance with a known trick — breaker location, reset button, quirk?',1),
('hot_tub_instructions','Hot tub instructions & hours','amenities',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'has_hot_tub',true,'maintenance_emergency_contact',NULL,'How is the hot tub operated, what are its hours, and any safety notes?',1),
('parking','Parking type & location','parking',false,'text',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"booking","pre-arrival","check-in"}'::text[],365,'brain_values','value',false,3.0,true,'always',true,'parking_overflow_fallback','Amenities section; ''Free parking on premises'' / ''Paid parking'' rows.','Where exactly do guests park — driveway, street, garage, assigned spot? Include the quirks.',1),
('wifi_network_name','Wi-Fi network name','connectivity',false,'string',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"pre-arrival","check-in","mid-stay"}'::text[],180,'brain_values','value',false,2.0,false,'has_wifi',true,'wifi_troubleshooting','Amenities section; look for ''Wifi'' or ''Internet'' amenity rows.','What is the exact Wi-Fi network name (SSID) guests should join?',1),
('wifi_password','Wi-Fi password','connectivity',false,'secret',NULL,'stay_scoped_secret'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay"}'::text[],180,'brain_values','secret_ref_or_ciphertext',true,3.0,true,'has_wifi',true,'wifi_troubleshooting',NULL,'What is the Wi-Fi password? It is stored encrypted and never sent to a model.',1)
ON CONFLICT (field_id) DO UPDATE SET label=EXCLUDED.label,domain=EXCLUDED.domain,system_section=EXCLUDED.system_section,type=EXCLUDED.type,enum_values=EXCLUDED.enum_values,sensitivity_tier=EXCLUDED.sensitivity_tier,default_audience=EXCLUDED.default_audience,phase=EXCLUDED.phase,ttl_days=EXCLUDED.ttl_days,storage_table=EXCLUDED.storage_table,storage_column=EXCLUDED.storage_column,storage_vault=EXCLUDED.storage_vault,gap_weight=EXCLUDED.gap_weight,hard_block=EXCLUDED.hard_block,applicability=EXCLUDED.applicability,requires_on_failure=EXCLUDED.requires_on_failure,on_failure_field=EXCLUDED.on_failure_field,scrape_hint=EXCLUDED.scrape_hint,interview_prompt=EXCLUDED.interview_prompt,registry_version=EXCLUDED.registry_version;
