INSERT INTO public.field_registry (field_id,label,domain,system_section,type,enum_values,sensitivity_tier,default_audience,phase,ttl_days,storage_table,storage_column,storage_vault,gap_weight,hard_block,applicability,requires_on_failure,on_failure_field,scrape_hint,interview_prompt,registry_version) VALUES
('door_code_or_entry_method','Door / access code','access_security',false,'secret',NULL,'stay_scoped_secret'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay"}'::text[],90,'brain_values','secret_ref_or_ciphertext',true,3.0,true,'always',true,'access_backup_method',NULL,'What is the door or building access code? Stored encrypted; never auto-sent.',1),
('elevator_stairs','Elevator or stairs','space_details',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","pre-arrival"}'::text[],365,'brain_values','value',false,1.0,false,'is_multi_story',false,NULL,'Accessibility features section.','Is there an elevator, or how many flights of stairs?',1),
('entry_method','Entry method / lock type','access_security',false,'enum','["smart_lock", "keypad", "lockbox", "physical_key", "doorman", "other"]'::jsonb,'guest_after_verification'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"pre-arrival","check-in"}'::text[],365,'brain_values','value',false,2.0,false,'always',true,'access_backup_method',NULL,'How do guests get in — smart lock, keypad, lockbox, key handoff, or doorman?',1),
('extra_guest_policy','Extra guest & visitor policy','house_rules',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking","mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'Are visitors or additional guests allowed, and at what cost?',1),
('floor_number','Floor number','space_details',false,'string',NULL,'public_guest'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"pre-arrival","check-in"}'::text[],365,'brain_values','value',false,0.5,false,'is_multi_story',false,NULL,NULL,'Which floor is the unit on?',1),
('key_return_process','Key or code return','checkout',false,'text',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"checkout"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'How are keys returned, or is the code simply retired?',1),
('late_checkout_policy','Late checkout policy','checkout',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_prearrival'::public.audience_tier,'{"mid-stay","checkout"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'Can a guest check out late, and is there a fee?',1),
('laundry_access','Laundry access & instructions','amenities',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'has_laundry',false,NULL,'Amenities section; ''Washer'' / ''Dryer'' rows.','Is there laundry, where is it, and how is it operated?',1),
('maintenance_emergency_contact','Maintenance / emergency contact','maintenance_escalation',false,'contact',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay","checkout"}'::text[],180,'brain_values','value',false,3.0,true,'always',false,NULL,NULL,'Who does a guest reach for an urgent maintenance problem, and on what number? This anchors every other fallback.',1),
('max_occupancy','Maximum occupancy','space_details',false,'number',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,1.0,false,'always',false,NULL,'Listing header; ''N guests'' in the summary row.','How many guests can stay?',1),
('minimum_stay','Minimum stay','policies_money',false,'number',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,0.5,false,'always',false,NULL,NULL,'What is the minimum number of nights?',1),
('nearest_grocery','Nearest grocery','local_area',false,'place',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"pre-arrival","mid-stay"}'::text[],180,'brain_values','value',false,3.0,true,'always',false,NULL,'Neighborhood / ''Where you''''ll be'' section.','What is the closest grocery store, and how far is it?',1),
('nearest_pharmacy','Nearest pharmacy','local_area',false,'place',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"mid-stay"}'::text[],180,'brain_values','value',false,1.0,false,'always',false,NULL,NULL,'What is the closest pharmacy, and how far is it?',1),
('parking_access_instructions','Parking access instructions','parking',false,'text',NULL,'guest_after_verification'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'has_parking',false,NULL,NULL,'Any gate code, permit, or garage clearance height guests need?',1),
('parking_cost','Parking cost','parking',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_public'::public.audience_tier,'{"booking"}'::text[],365,'brain_values','value',false,0.5,false,'has_parking',false,NULL,NULL,'Is parking free or paid, and how much?',1),
('parking_overflow_fallback','Parking fallback','parking',false,'text',NULL,'public_guest'::public.sensitivity_tier,'guest_instay'::public.audience_tier,'{"check-in","mid-stay"}'::text[],365,'brain_values','value',false,1.0,false,'has_parking',false,NULL,NULL,'If the spot is taken or the garage is full, where should a guest go instead?',1)
ON CONFLICT (field_id) DO UPDATE SET label=EXCLUDED.label,domain=EXCLUDED.domain,system_section=EXCLUDED.system_section,type=EXCLUDED.type,enum_values=EXCLUDED.enum_values,sensitivity_tier=EXCLUDED.sensitivity_tier,default_audience=EXCLUDED.default_audience,phase=EXCLUDED.phase,ttl_days=EXCLUDED.ttl_days,storage_table=EXCLUDED.storage_table,storage_column=EXCLUDED.storage_column,storage_vault=EXCLUDED.storage_vault,gap_weight=EXCLUDED.gap_weight,hard_block=EXCLUDED.hard_block,applicability=EXCLUDED.applicability,requires_on_failure=EXCLUDED.requires_on_failure,on_failure_field=EXCLUDED.on_failure_field,scrape_hint=EXCLUDED.scrape_hint,interview_prompt=EXCLUDED.interview_prompt,registry_version=EXCLUDED.registry_version;
