-- Migration: add human-quotable stay_reference to public.stays
-- Date: 2026-08-26
-- Plan: planning/reports-rework-execution-plan-2026-08-26.md (section 3)
-- Reversible: ALTER TABLE public.stays DROP COLUMN stay_reference;
--
-- Why: report filtering/display needs a quotable stay identifier. The 4-digit
-- visit codes stay HMAC-hashed secrets (guest_access_links.code_hash) and are
-- never report data. stay_reference is the displayable counterpart, generated
-- by application code at stay creation (same pattern as
-- extras_orders.request_number).
--
-- Applied to production Supabase (project sqpdzhannyskdiyuarhp) on 2026-08-26
-- as migration "add_stay_reference".

BEGIN;

-- 1. Add column (nullable during backfill)
ALTER TABLE public.stays
  ADD COLUMN IF NOT EXISTS stay_reference text;

-- 2. Backfill existing rows (6-char hex from uuid; 16^6 = 16.7M space, a
--    handful of live rows, so collision probability is negligible. If the
--    unique index below ever failed on backfill, re-running this UPDATE
--    resolves it.)
UPDATE public.stays
SET stay_reference = 'STY-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
WHERE stay_reference IS NULL;

-- 3. Constrain
ALTER TABLE public.stays
  ALTER COLUMN stay_reference SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS stays_stay_reference_key
  ON public.stays (stay_reference);

COMMENT ON COLUMN public.stays.stay_reference IS
  'Human-quotable stay reference (STY-XXXXXX). Generated by application code at stay creation; unique globally. Displayable/filterable counterpart to the HMAC-hashed 4-digit visit code, which is never stored in plaintext.';

COMMIT;

-- App-side obligation (not in SQL): stay-creation code generates
-- 'STY-' + 6 chars from an unambiguous uppercase alphabet (no 0/O, 1/I/L),
-- with insert-retry on unique-violation, mirroring the visit-code generator.
-- Surface stay_reference on the welcome card and stay screens.
